const shortDescriptions = {


// A: logical connectives
"e": "and",
"ji": "(connective ???)",
"o": "if and only if",
"a": "or",
"u": "whether or not",

// JA: logical connectives
"je": "and",
"je'i": "(connective ???)",
"jo": "if and only if",
"ja": "or",
"ju": "whether or not",

// JOI: non-logical connectives
"joi": "and (mixed together)",

// BAI: sumtcita
"du'o": "according to",
"si'u": "aided by",
"zau": "approved by",
"ki'i": "as a relation of",
"du'i": "as much as",
"cu'u": "as said by",
"tu'i": "associated with site",
"ti'u": "associated with time",
"di'o": "at the locus of",
"ji'u": "based on",
"ri'a": "because of cause",
"ni'i": "because of logic",
"mu'i": "because of motive",
"ki'u": "because of reason",
"va'u": "benefiting from",
"koi": "bounded by",
"ca'i": "by authority of",
"ta'i": "by method",
"pu'e": "by process",
"ja'i": "by rule",
"kai": "characterizing",
"bai": "compelled by",
"fi'e": "created by",
"de'i": "dated",
"ci'o": "emotionally felt by",
"mau": "exceeded by",
"mu'u": "exemplified by",
"ri'i": "experienced by",
"ra'i": "from source",
"ka'a": "gone to by",
"pa'u": "having component",
"pa'a": "in addition to",
"le'a": "in category",
"ku'u": "in culture",
"tai": "in form",
"bau": "in language",
"ma'i": "in reference frame",
"ci'e": "in system",
"fau": "in the event of",
"po'i": "in the sequence",
"cau": "lacked by",
"ma'e": "material object",
"ci'u": "on the scale",
"ra'a": "pertained to by",
"pu'a": "pleased by",
"li'e": "preceded by",
"la'u": "quantifying",
"ba'i": "replaced by",
"ka'i": "represented by",
"sau": "requiring",
"fa'e": "reverse of",
"be'i": "sent by",
"ti'i": "suggested by",
"ja'e": "therefore result",
"ga'a": "to observer",
"va'o": "under conditions",
"ji'o": "under direction of",
"me'a": "undercut by",
"do'e": "(unspecified modal)",
"ji'e": "up to limit",
"pi'o": "used by",
"gau": "with active agent",
"zu'e": "with actor",
"me'e": "with name",
"rai": "with superlative",

// BAhE: emphasis
"ba'e": "(emphasized)",
"za'e": "(nonce)",

// BE: first attached sumti
"be": "(link sumti)",

// BEI: next attached sumti
"bei": "(more sumti)",

// BEhO: fa'orma'o for BE ... BEI
"be'o": "(end sumti)",

// BIhE: high priority
"bi'e": "(high priority)",

// BIhI: non-logical interval connectives
"mi'i": "(ordered) ... center",
"bi'o": "(ordered) from ... to ...",
"bi'i": "(unordered) between ... and ...",

// BO: short scope
"bo": "(short scope link)",

// BOI: end numeral or letteral string
"boi": "(end string)",

// BU: convert word to letteral
"bu": "(letter)",

// BY: letterals
"by": "B",
"cy": "C",
"dy": "D",
"fy": "F",
"gy": "G",
"jy": "J",
"ky": "K",
"ly": "L",
"my": "M",
"ny": "N",
"py": "P",
"ry": "R",
"sy": "S",
"ty": "T",
"vy": "V",
"xy": "X",
"y'y": "'",
"zy": "Z",

/*
"ga'e": "BY1",
"ge'o": "BY1",
"je'o": "BY1",
"jo'o": "BY1",
"lo'a": "BY1",
"na'a": "BY1",
"ru'o": "BY1",
"se'e": "BY1",
"to'a": "BY1",


// COI: vocative with meaning
"coi": "COI",
"co'o": "COI",
"je'e": "COI",
"nu'e": "COI",
"ju'i": "COI",
"ta'a": "COI",
"pe'u": "COI",
"ki'e": "COI",
"fi'i": "COI",
"be'e": "COI",
"re'i": "COI",
"mu'o": "COI",
"vi'o": "COI",
"ke'o": "COI",
"fe'o": "COI",
"mi'e": "COI",

// CU: separate selbri from preceding sumti
"cu": "CU",

// DOI: vocative without meaning
"doi": "DOI",

// FEhU: fa'orma'o for FIhO
"fe'u": "FEhU",

// FIhO: start modal tag
"fi'o": "FIhO",

// GEhU: fa'orma'o for GOI
"ge'u": "GEhU",

// GOhA: pro-selbri
"mo": "GOhA",
"nei": "GOhA",
"go'u": "GOhA",
"go'o": "GOhA",
"go'i": "GOhA",
"no'a": "GOhA",
"go'e": "GOhA",
"go'a": "GOhA",
"du": "GOhA",
"bu'a": "GOhA",
"bu'e": "GOhA",
"bu'i": "GOhA",
"co'e": "GOhA",

// GOI: relative phrase
"pe": "GOI",
"po": "GOI",
"po'e": "GOI",
"po'u": "GOI",
"ne": "GOI",
"no'u": "GOI",

// JOI: non-logical connectives (for all except bridi)
"ce": "JOI",
"ce'o": "JOI",
"fa'u": "JOI",
"jo'e": "JOI",
"jo'u": "JOI",
"joi": "JOI",
"ju'e": "JOI",
"ku'a": "JOI",
"pi'u": "JOI",
"ce'oi": "JOI",

// KOhA*: sumka'i
"da": "KOhA1",
"de": "KOhA1",
"di": "KOhA1",
"da'u": "KOhA2",
"da'e": "KOhA2",
"di'u": "KOhA2",
"di'e": "KOhA2",
"de'u": "KOhA2",
"de'e": "KOhA2",
"dei ": "KOhA2",
"do'i": "KOhA2",
"ko": "KOhA3",
"mi": "KOhA3",
"mi'o": "KOhA3",
"ma'a": "KOhA3",
"mi'a": "KOhA3",
"do": "KOhA3",
"do'o": "KOhA3",
"ko'a": "KOhA4",
"fo'u": "KOhA4",
"ko'e": "KOhA4",
"ko'i": "KOhA4",
"ko'o": "KOhA4",
"ko'u": "KOhA4",
"fo'a": "KOhA4",
"fo'e": "KOhA4",
"fo'i": "KOhA4",
"fo'o": "KOhA4",
"vo'a": "KOhA4",
"vo'e": "KOhA4",
"vo'i": "KOhA4",
"vo'o": "KOhA4",
"vo'u": "KOhA4",
"ru": "KOhA5",
"ri": "KOhA5",
"ra": "KOhA5",
"ta": "KOhA6",
"tu": "KOhA6",
"ti": "KOhA6",
"zi'o": "KOhA7",
"ke'a": "KOhA7",
"ma": "KOhA7",
"zu'i": "KOhA7",
"zo'e": "KOhA7",
"ce'u": "KOhA8",

// KU: fa'orma'o for LE and unfilled tags
"ku": "KU",

// KUhO: fa'orma'o for NOI
"ku'o": "KUhO",

// LA: gadri for names
"la": "LA",
"lai": "LA",
"la'i": "LA",

// LE: gadri for objects
"le": "LE",
"lei": "LE",
"loi": "LE",
"lo": "LE",
"le'i": "LE",
"lo'i": "LE",
"le'e": "LE",
"lo'e": "LE",

// LI: gadri for numbers
"li": "LI",
"me'o": "LI",
"li'ai": "LI",

// LIhU: fa'orma'o for LU
"li'u": "LIhU",

// LU: grammatical quote
"lu": "LU",
"la'au": "LU",

// MOI
"mei": "MOI",
"moi": "MOI",
"si'e": "MOI",
"cu'o": "MOI",

// NOI: relative clauses
"noi": "NOI",
"poi": "NOI",
"voi": "NOI",

// NU: abstractors
"du'u": "NU",
"jei": "NU",
"ka": "NU",
"jei": "NU",
"li'i": "NU",
"mu'e": "NU",
"ni": "NU",
"nu": "NU",
"pu'u": "NU",
"si'o": "NU",
"su'u": "NU",
"za'i": "NU",
"zu'o": "NU",

"ba": "PU",
"pu": "PU",
"ca": "PU",

"se": "SE",
"te": "SE",
"ve": "SE",
"xe": "SE",

// UI: indicators
"i'a": "UI1",
"ie": "UI1",
"a'e": "UI1",
"u'i": "UI1",
"i'o": "UI1",
"i'e": "UI1",
"a'a": "UI1",
"ia ": "UI1",
"o'i": "UI1",
"o'e": "UI1",
"e'e": "UI1",
"oi": "UI1",
"uo": "UI1",
"e'i": "UI1",
"u'o": "UI1",
"au": "UI1",
"ua": "UI1",
"a'i": "UI1",
"i'u": "UI1",
"ii": "UI1",
"u'a": "UI1",
"ui": "UI1",
"a'o": "UI1",
"ai": "UI1",
"a'u": "UI1",
"iu": "UI1",
"ei": "UI1",
"o'o": "UI1",
"e'a": "UI1",
"uu": "UI1",
"o'a": "UI1",
"o'u": "UI1",
"u'u": "UI1",
"e'o": "UI1",
"io": "UI1",
"e'u": "UI1",
"ue": "UI1",
"i'i": "UI1",
"u'e": "UI1",

"ki'a": "UI6",
"xu": "UI6",

"vi": "VA",
"va": "VA",
"vu": "VA",

// ZIhE: join relatives
"zi'e": "ZIhE",

// ZOI: non-Lojban quotes
"zoi": "ZOI",
"la'o": "ZOI",


*/



// pro-sumti
"mi": "I; me",
"do": "you",
"ko": "you (!)",
"ti": "this",
"ta": "that",
"tu": "that there",
"ma": "(sumti ???)",
"ke'a": "(relative reference)",

// descriptors
"la": "the one named",
"le": "the",
"li": "the number",
"lo": "a; some",

// attitudinals
"ui": "(happy)",

// vocatives
"coi": "hello",
"doi": "(vocative)",
"mi'e": "I am",
"je'e": "okay",
"co'o": "goodbye",

// tenses
"pu": "did; before",
"ca": "now; while",
"ba": "will; after",

// abstractors
"du'u": "expression of", // TODO expression?
"nu": "event of",

// numbers
"pa": "1",
"re": "2",
"ci": "3",
"vo": "4",
"mu": "5",
"xa": "6",
"ze": "7",
"bi": "8",
"so": "9",
"no": "0",
"ro": "all (of)",

// quotes
"lu": "\"",
"li'u": "\"",
"zo": "(word quote)",
"zoi": "(non-Lojban quote)",

// various cmavo
"fa": "(place 1)",
"fe": "(place 2)",
"fi": "(place 3)",
"fo": "(place 4)",
"fu": "(place 5)",
"se": "(swap 1 & 2)",
"te": "(swap 1 & 3)",
"ve": "(swap 1 & 4)",
"xe": "(swap 1 & 5)",
"cu": "",
"zo'e": "something",
"na": "not",
"nai": "(negation)",
"i": ".",
"ni'o": "(new topic)",
"no'i": "(old topic)",
"xu": "(yes/no ???)",

// pro-selbri
"du": "to be equal to",
"mo": "(selbri ???)",

// gismu
"bacru": "to say; to utter",
"badna": "banana",
"badri": "sad",
"bajra": "to run",
"bakfu": "bundle",
"bakni": "bovine",
"bakri": "chalk",
"baktu": "bucket",
"balji": "bulb",
"balni": "balcony",
"balre": "blade",
"balvi": "(in the) future",
"bancu": "beyond",
"bandu": "defend",
"banfi": "amphibian",
"bangu": "language",
"banli": "great",
"banro": "to grow",
"banxa": "bank",
"banzu": "to suffice",
"bapli": "to force",
"barda": "big",
"bargu": "arch",
"barja": "bar",
"barna": "mark",
"bartu": "out",
"basna": "to emphasize",
"basti": "to replace",
"batci": "to bite",
"batke": "button",
"bavmi": "barley",
"baxso": "Malay-Indonesian",
"bebna": "foolish",
"bemro": "North American",
"bende": "crew",
"bengo": "Bengali",
"benji": "to transfer",
"bersa": "son",
"berti": "north",
"besna": "brain",
"betfu": "abdomen",
"betri": "tragedy",
"bevri": "carry",
"bidju": "bead",
"bifce": "bee",
"bikla": "whip",
"bilga": "obliged",
"bilma": "ill",
"bilni": "military",
"bindo": "Indonesian",
"binra": "to insure",
"binxo": "to become",
"birje": "beer",
"birka": "arm",
"birti": "certain",
"bisli": "ice",
"bitmu": "wall",
"blabi": "white",
"blaci": "glass",
"blanu": "blue",
"bliku": "block",
"bloti": "boat",
"bolci": "ball",
"bongu": "bone",
"botpi": "bottle",
"boxfo": "sheet",
"boxna": "wave",
"bradi": "enemy",
"bratu": "hail",
"brazo": "Brazilian",
"bredi": "ready",
"bridi": "predicate",
"brife": "breeze",
"briju": "office",
"brito": "British",
"broda": "(predicate variable 1)",
"brode": "(predicate variable 2)",
"brodi": "(predicate variable 3)",
"brodo": "(predicate variable 4)",
"brodu": "(predicate variable 5)",
"bruna": "brother",
"budjo": "Buddhist",
"bukpu": "cloth",
"bumru": "fog",
"bunda": "pound",
"bunre": "brown",
"burcu": "brush",
"burna": "embarrassed",
"cabna": "now",
"cabra": "apparatus",
"cacra": "hour", // TODO to be in?????? see djedi, nanca, masti
"cadzu": "to walk",
"cafne": "often",
"cakla": "chocolate",
"calku": "shell",
"canci": "to vanish",
"cando": "idle",
"cange": "farm",
"canja": "to exchange",
"canko": "window",
"canlu": "space",
"canpa": "shovel",
"canre": "sand",
"canti": "gut",
"carce": "cart",
"carmi": "intense",
"carna": "to turn",
"cartu": "chart",
"carvi": "rain",
"casnu": "to discuss",
"catke": "to shove",
"catlu": "to look",
"catni": "authority",
"catra": "to kill",
"caxno": "shallow",
"cecla": "launcher",
"cecmu": "community",
"cedra": "era",
"cenba": "to vary",
"censa": "holy",
"centi": ".01",
"cerda": "heir",
"cerni": "morning",
"certu": "expert",
"cevni": "god",
"cfari": "to initiate",
"cfika": "fiction",
"cfila": "flaw",
"cfine": "wedge",
"cfipu": "confusing",
"ciblu": "blood",
"cicna": "cyan",
"cidja": "food",
"cidni": "knee",
"cidro": "hydrogen",
"cifnu": "infant",
"cigla": "gland",
"cikna": "awake",
"cikre": "to repair",
"ciksi": "to explain",
"cilce": "wild",
"cilmo": "moist",
"cilre": "to learn",
"cilta": "thread",
"cimde": "dimension",
"cimni": "infinite",
"cinba": "to kiss",
"cindu": "oak",
"cinfo": "lion",
"cinje": "to wrinkle",
"cinki": "insect",
"cinla": "thin",
"cinmo": "emotion",
"cinri": "interesting",
"cinse": "sexual",
"cinta": "paint",
"cinza": "tongs",
"cipni": "bird",
"cipra": "test",
"cirko": "to lose",
"cirla": "cheese",
"ciska": "to write",
"cisma": "smile",
"ciste": "system",
"citka": "to eat",
"citno": "young",
"citri": "history",
"citsi": "season",
"civla": "louse",
"cizra": "strange",
"ckabu": "rubber",
"ckafi": "coffee",
"ckaji": "quality",
"ckana": "bed",
"ckape": "peril",
"ckasu": "ridicule",
"ckeji": "ashamed",
"ckiku": "key",
"ckilu": "scale",
"ckini": "related",
"ckire": "grateful",
"ckule": "school",
"ckunu": "conifer",
"cladu": "loud",
"clani": "long",
"claxu": "without",
"clika": "mossy",
"clira": "early",
"clite": "polite",
"cliva": "to leave",
"clupa": "loop",
"cmaci": "mathematics",
"cmalu": "small",
"cmana": "mountain",
"cmavo": "(Lojban) cmavo",
"cmene": "name",
"cmila": "to laugh",
"cmima": "member",
"cmoni": "moan",
"cnano": "norm",
"cnebo": "neck",
"cnemu": "to reward",
"cnici": "orderly",
"cnino": "new",
"cnisa": "lead",
"cnita": "beneath",
"cokcu": "to soak up",
"condi": "deep",
"cortu": "pain",
"cpacu": "to get",
"cpana": "upon",
"cpare": "to climb",
"cpedu": "to request",
"cpina": "pungent",
"cradi": "radio",
"crane": "front",
"creka": "shirt",
"crepu": "to harvest",
"cribe": "bear",
"crida": "fairy",
"crino": "green",
"cripu": "bridge",
"crisa": "summer",
"critu": "autumn",
"ctaru": "tide",
"ctebi": "lip",
"cteki": "tax",
"ctile": "petroleum",
"ctino": "shadow",
"ctuca": "to teach",
"cukla": "round",
"cukta": "book",
"culno": "full",
"cumki": "possible",
"cumla": "humble",
"cunmi": "millet",
"cunso": "random",
"cuntu": "affair",
"cupra": "to produce",
"curmi": "to let; to permit",
"curnu": "worm",
"curve": "pure",
"cusku": "to express; to say",
"cutci": "shoe",
"cutne": "chest",
"cuxna": "to choose",
"dacru": "drawer",
"dacti": "object",
"dadjo": "Taoist",
"dakfu": "knife",
"dakli": "sack",
"damba": "to fight",
"damri": "drum",
"dandu": "hang",
"danfu": "answer",
"danlu": "animal",
"danmo": "smoke",
"danre": "pressure",
"dansu": "to dance",
"danti": "projectile",
"daplu": "island",
"dapma": "to curse",
"dargu": "road",
"darlu": "to argue",
"darno": "far",
"darsi": "audacity",
"darxi": "to hit",
"daski": "pocket",
"dasni": "to wear",
"daspo": "to destroy",
"dasri": "ribbon",
"datka": "duck",
"datni": "data",
"decti": ".1",
"degji": "finger",
"dejni": "owe",
"dekpu": "gallon",
"dekto": "10",
"delno": "candela",
"dembi": "bean",
"denci": "tooth",
"denmi": "dense",
"denpa": "to wait",
"dertu": "dirt",
"derxi": "heap",
"desku": "to shake",
"detri": "date",
"dicra": "to interrupt",
"dikca": "electric",
"diklo": "local",
"dikni": "regular",
"dilcu": "quotient",
"dilnu": "cloud",
"dimna": "fate",
"dinju": "building",
"dinko": "nail",
"dirba": "dear",
"dirce": "to radiate",
"dirgo": "drop",
"dizlo": "low",
"djacu": "water",
"djedi": "(to be in) day(s)",
"djica": "to desire; to want",
"djine": "ring",
"djuno": "to know",
"donri": "daytime",
"dotco": "German",
"draci": "drama",
"drani": "correct",
"drata": "other",
"drudi": "roof",
"dugri": "logarithm",
"dukse": "to excess",
"dukti": "opposite",
"dunda": "to give",
"dunja": "to freeze",
"dunku": "anguished; stressed",
"dunli": "to be equal to",
"dunra": "winter",
"dzena": "elder",
"dzipo": "Antarctican",
"facki": "to discover",
"fadni": "ordinary",
"fagri": "fire",
"falnu": "sail",
"famti": "aunt; uncle",
"fancu": "function",
"fange": "alien",
"fanmo": "end",
"fanri": "factory",
"fanta": "to prevent",
"fanva": "to translate",
"fanza": "to annoy",
"fapro": "to oppose",
"farlu": "to fall",
"farna": "direction",
"farvi": "to develop",
"fasnu": "event",
"fatci": "fact",
"fatne": "to reverse",
"fatri": "to distribute",
"febvi": "to boil",
"femti": "1E-15",
"fendi": "to divide",
"fengu": "angry",
"fenki": "crazy",
"fenra": "crack",
"fenso": "to sew",
"fepni": "cent",
"fepri": "lung",
"ferti": "fertile",
"festi": "waste",
"fetsi": "female",
"figre": "fig",
"filso": "Palestinian",
"finpe": "fish",
"finti": "to invent",
"flalu": "law",
"flani": "flute",
"flecu": "flow",
"fliba": "to fail",
"flira": "face",
"foldi": "field",
"fonmo": "foam",
"fonxa": "telephone",
"forca": "fork",
"fraso": "French",
"frati": "to react",
"fraxu": "to forgive",
"frica": "to differ",
"friko": "African",
"frili": "easy",
"frinu": "fraction",
"friti": "to offer",
"frumu": "to frown",
"fukpi": "to copy",
"fulta": "to float",
"funca": "luck",
"fusra": "rotten",
"fuzme": "responsible",
"gacri": "cover",
"gadri": "article",
"galfi": "to modify",
"galtu": "high",
"galxe": "throat",
"ganlo": "closed",
"ganra": "broad",
"ganse": "to sense",
"ganti": "gonad",
"ganxo": "anus",
"ganzu": "to organize",
"gapci": "gas",
"gapru": "above",
"garna": "rail",
"gasnu": "to do",
"gasta": "steel",
"genja": "root",
"gento": "Argentinian",
"genxu": "hook",
"gerku": "dog",
"gerna": "grammar",
"gidva": "to guide",
"gigdo": "1E9",
"ginka": "camp",
"girzu": "group",
"gismu": "(Lojban) gismu",
"glare": "hot",
"gleki": "happy",
"gletu": "to copulate",
"glico": "English",
"gluta": "glove",
"gocti": "1E-24",
"gotro": "1E24",
"gradu": "unit",
"grake": "gram",
"grana": "rod",
"grasu": "grease",
"greku": "frame",
"grusi": "gray",
"grute": "fruit",
"gubni": "public",
"gugde": "country",
"gundi": "industry",
"gunka": "to work",
"gunma": "jointly",
"gunro": "to roll",
"gunse": "goose",
"gunta": "to attack",
"gurni": "grain",
"guska": "to scrape; to erode",
"gusni": "light; to illumine",
"gusta": "restaurant",
"gutci": "cubit",
"gutra": "womb",
"guzme": "melon",
"jabre": "to brake",
"jadni": "to decorate",
"jakne": "rocket",
"jalge": "result",
"jalna": "starch",
"jalra": "cockroach",
"jamfu": "foot",
"jamna": "to war",
"janbe": "bell",
"janco": "shoulder",
"janli": "to collide",
"jansu": "diplomat",
"janta": "account",
"jarbu": "suburb",
"jarco": "to show",
"jarki": "narrow",
"jaspu": "passport",
"jatna": "captain",
"javni": "rule",
"jbama": "bomb",
"jbari": "berry",
"jbena": "born",
"jbera": "to borrow",
"jbini": "between",
"jdari": "firm",
"jdice": "to decide",
"jdika": "to decrease",
"jdima": "price",
"jdini": "money",
"jduli": "jelly",
"jecta": "polity",
"jeftu": "week",
"jegvo": "Jehovist",
"jelca": "to burn",
"jemna": "gem",
"jenca": "to shock",
"jendu": "axle",
"jenmi": "army",
"jerna": "to earn",
"jersi": "to chase",
"jerxo": "Algerian",
"jesni": "needle",
"jetce": "jet",
"jetnu": "true",
"jgalu": "claw",
"jganu": "angle",
"jgari": "to grasp; to hold",
"jgena": "knot",
"jgina": "gene",
"jgira": "pride",
"jgita": "guitar",
"jibni": "near",
"jibri": "job",
"jicla": "stir",
"jicmu": "basis",
"jijnu": "intuit",
"jikca": "to socialize",
"jikru": "liquor",
"jilka": "alkali",
"jilra": "jealous",
"jimca": "branch",
"jimpe": "to understand",
"jimte": "limit",
"jinci": "shears",
"jinga": "to win",
"jinku": "vaccine",
"jinme": "metal",
"jinru": "to immerse",
"jinsa": "clean",
"jinto": "well; spring",
"jinvi": "to opine",
"jinzi": "innate property",
"jipci": "chicken",
"jipno": "tip",
"jirna": "horn",
"jisra": "juice",
"jitfa": "false",
"jitro": "to control; to manage",
"jivbu": "to weave",
"jivna": "to compete",
"jmaji": "to gather",
"jmifa": "shoal",
"jmina": "to add",
"jmive": "to live",
"jordo": "Jordanian",
"jorne": "joined",
"jubme": "table",
"judri": "address",
"jufra": "sentence; text",
"jukni": "spider",
"jukpa": "to cook",
"julne": "net",
"jundi": "attentive",
"jungo": "Chinese",
"junla": "clock",
"junri": "serious",
"junta": "weight",
"jurme": "germ",
"jursa": "severe",
"jutsi": "species",
"juxre": "clumsy",
"jvinu": "view",
"kabri": "cup",
"kacma": "camera",
"kadno": "Canadian",
"kafke": "to cough",
"kagni": "company",
"kajde": "to warn",
"kajna": "shelf",
"kakne": "to be able to",
"kakpa": "to dig",
"kalci": "feces",
"kalri": "open",
"kalsa": "chaotic",
"kalte": "to hunt",
"kamju": "column",
"kamni": "committee",
"kampu": "common",
"kanba": "goat",
"kancu": "to count",
"kandi": "dim",
"kanji": "calculate",
"kanla": "eye",
"kanro": "healthy",
"kansa": "with",
"kantu": "quantum",
"kanxe": "conjunction",
"karbi": "to compare",
"karce": "car",
"karda": "card",
"kargu": "costly",
"karli": "collar",
"karni": "journal",
"katna": "to cut",
"kavbu": "to capture",
"kecti": "pity",
"kelci": "to play",
"kelvo": "kelvin",
"kenra": "cancer",
"kensa": "outer space",
"kerfa": "hair",
"kerlo": "ear",
"ketco": "South American",
"kevna": "cavity",
"kibro": "internet",
"kicne": "cushion",
"kijno": "oxygen",
"kilto": "1000",
"kinda": "kind of",
"kinli": "sharp",
"kisto": "Pakistani",
"klaji": "street",
"klaku": "to weep",
"klama": "to come",
"klani": "quantity",
"klesi": "class",
"klina": "clear",
"kliru": "chlorine",
"kliti": "clay",
"klupe": "screw",
"kluza": "loose",
"kobli": "cabbage",
"kojna": "corner",
"kolme": "coal",
"komcu": "to comb",
"konju": "cone",
"korbi": "edge",
"korcu": "bent",
"korka": "cork",
"kosta": "coat",
"kramu": "acre",
"krasi": "source",
"krati": "to represent",
"krefu": "recurrence; repetition",
"krici": "to believe",
"krili": "crystal",
"krinu": "reason",
"krixa": "to cry out",
"kruca": "to intersect",
"kruji": "cream",
"kruvi": "curve",
"kubli": "cube",
"kucli": "curious",
"kufra": "comfort",
"kukte": "delicious",
"kulnu": "culture",
"kumfa": "room",
"kumte": "camel",
"kunra": "mineral",
"kunti": "empty",
"kurfa": "square",
"kurji": "to take care of",
"kurki": "bitter",
"kuspe": "to range; to span",
"kusru": "cruel",
"labno": "wolf",
"lacpu": "to pull",
"lacri": "to rely",
"ladru": "milk",
"lafti": "lift",
"lakne": "probable",
"lakse": "wax",
"lalxu": "lake",
"lamji": "adjacent",
"lanbi": "protein",
"lanci": "flag",
"lanka": "basket",
"lanli": "to analyze",
"lanme": "sheep",
"lante": "can",
"lanxe": "to balance",
"lanzu": "family",
"larcu": "art",
"lasna": "to fasten",
"lastu": "brass",
"latmo": "Latin",
"latna": "lotus",
"lazni": "lazy",
"lebna": "to take",
"lenjo": "lens",
"lenku": "cold",
"lerci": "late",
"lerfu": "letteral",
"libjo": "Libyan",
"lidne": "to precede",
"lifri": "to experience",
"lijda": "religion",
"limna": "to swim",
"lindi": "lightning",
"linji": "line",
"linsi": "chain",
"linto": "lightweight",
"lisri": "story",
"liste": "list",
"litce": "liter",
"litki": "liquid",
"litru": "to travel",
"livga": "liver",
"livla": "fuel",
"logji": "logic",
"lojbo": "Lojbanic",
"loldi": "floor",
"lorxu": "fox",
"lubno": "Lebanese",
"lujvo": "(Lojban) lujvo",
"lumci": "to wash",
"lunbe": "bare",
"lunra": "lunar",
"lunsa": "to condense",
"mabla": "derogative",
"mabru": "mammal",
"macnu": "manual",
"makcu": "mature",
"makfa": "magic",
"maksi": "magnet",
"malsi": "temple",
"mamta": "mother",
"manci": "to wonder",
"manfo": "uniform",
"manku": "dark",
"manri": "reference",
"mansa": "to satisfy",
"manti": "ant",
"mapku": "cap",
"mapni": "cotton",
"mapti": "to fit",
"marbi": "shelter",
"marce": "vehicle",
"marde": "ethics; morals",
"margu": "mercury",
"marji": "material",
"marna": "hemp",
"marxa": "to mash",
"masno": "slow",
"masti": "(to be in) month(s)",
"matci": "mat",
"matli": "linen",
"matne": "butter",
"matra": "motor",
"mavji": "oats",
"maxri": "wheat",
"mebri": "brow",
"megdo": "1E6",
"mekso": "mathematical expression",
"melbi": "beautiful",
"meljo": "Malaysian",
"menli": "mind",
"mensi": "sister",
"mentu": "minute",
"merko": "American",
"merli": "to measure",
"mexno": "Mexican",
"midju": "middle",
"mifra": "code",
"mikce": "doctor",
"mikri": "1E-6",
"milti": ".001",
"milxe": "mild",
"minde": "to command",
"minji": "machine",
"minli": "mile",
"minra": "to reflect",
"mintu": "same",
"mipri": "secret",
"mirli": "deer",
"misno": "famous",
"misro": "Egyptian",
"mitre": "meter",
"mixre": "mixture",
"mlana": "side",
"mlatu": "cat",
"mleca": "less",
"mledi": "mold",
"mluni": "satellite",
"mokca": "point",
"moklu": "mouth",
"molki": "mill",
"molro": "mole",
"morji": "to remember",
"morko": "Moroccan",
"morna": "pattern",
"morsi": "dead",
"mosra": "friction",
"mraji": "rye",
"mrilu": "to mail",
"mruli": "hammer",
"mucti": "immaterial",
"mudri": "wood",
"mukti": "motive",
"mulno": "complete",
"munje": "universe",
"mupli": "example",
"murse": "glimmering",
"murta": "curtain",
"muslo": "Islamic",
"mutce": "much",
"muvdu": "to move",
"muzga": "museum",
"nabmi": "problem",
"nakni": "male",
"nalci": "wing",
"namcu": "number",
"nanba": "bread",
"nanca": "(to be in) year(s)",
"nandu": "difficult",
"nanla": "boy",
"nanmu": "man",
"nanvi": "1E-9",
"narge": "nut",
"narju": "orange",
"natfe": "to deny",
"natmi": "nation",
"navni": "neon",
"naxle": "canal",
"nazbi": "nose",
"nejni": "energy",
"nelci": "to like",
"nenri": "in",
"nibli": "to necessitate",
"nicte": "night",
"nikle": "nickel",
"nilce": "furniture",
"nimre": "citrus",
"ninmu": "woman",
"nirna": "nerve",
"nitcu": "to need",
"nivji": "to knit",
"nixli": "girl",
"nobli": "noble",
"notci": "message",
"nukni": "magenta",
"nupre": "to promise",
"nurma": "rural",
"nutli": "neutral",
"nuzba": "news",
"pacna": "to hope",
"pagbu": "part",
"pagre": "pass through",
"pajni": "judge",
"palci": "evil",
"palku": "pants",
"palne": "tray",
"palpi": "palpate",
"palta": "plate",
"pambe": "pump",
"panci": "odor",
"pandi": "punctuate",
"panje": "sponge",
"panka": "park",
"panlo": "slice",
"panpi": "peace",
"panra": "parallel",
"pante": "to protest",
"panzi": "offspring",
"papri": "page",
"parbi": "ratio",
"pastu": "robe",
"patfu": "father",
"patlu": "potato",
"patxu": "pot",
"pelji": "paper",
"pelxu": "yellow",
"pemci": "poem",
"penbi": "pen",
"pencu": "to touch",
"pendo": "friend",
"penmi": "to meet",
"pensi": "to think",
"perli": "pear",
"pesxu": "paste",
"petso": "1E15",
"pezli": "leaf",
"picti": "1E-12",
"pijne": "pin",
"pikci": "to beg",
"pikta": "ticket",
"pilji": "to multiply",
"pilka": "crust",
"pilno": "to use",
"pimlu": "feather",
"pinca": "urine",
"pindi": "poor",
"pinfu": "prisoner",
"pinji": "penis",
"pinka": "to comment",
"pinsi": "pencil",
"pinta": "level",
"pinxe": "to drink",
"pipno": "piano",
"pixra": "picture",
"plana": "plump",
"platu": "to plan",
"pleji": "to pay",
"plibu": "pubic",
"plini": "planet",
"plipe": "to leap",
"plise": "apple",
"plita": "plane",
"plixa": "to plow",
"pluja": "complicated",
"pluka": "pleasant",
"pluta": "route",
"polje": "to fold",
"polno": "Polynesian",
"ponjo": "Japanese",
"ponse": "to own",
"porpi": "break",
"porsi": "sequence",
"porto": "Portuguese",
"prali": "to profit",
"prami": "to love",
"prane": "perfect",
"preja": "to spread",
"prenu": "person",
"preti": "question",
"prije": "wise",
"prina": "to print",
"pritu": "right",
"prosa": "prose",
"pruce": "process",
"pruni": "elastic",
"pruxi": "spirit",
"pulce": "dust",
"pulji": "police",
"pulni": "pulley",
"punji": "to put",
"punli": "swelling",
"purci": "past",
"purdi": "garden",
"purmo": "powder",
"racli": "sane",
"ractu": "rabbit",
"radno": "radian",
"rafsi": "affix",
"ragve": "across",
"rakso": "Iraqi",
"raktu": "to trouble",
"ralci": "delicate",
"ralju": "principal",
"ralte": "to retain",
"randa": "to yield",
"rango": "organ",
"ranji": "to continue",
"ranmi": "myth",
"ransu": "bronze",
"ranti": "soft",
"ranxi": "irony",
"rapli": "to repeat",
"rarna": "natural",
"ratcu": "rat",
"ratni": "atom",
"rebla": "tail",
"rectu": "meat",
"remna": "human",
"renro": "to throw",
"renvi": "to survive",
"respa": "reptile",
"ricfu": "rich",
"rigni": "disgusting",
"rijno": "silver",
"rilti": "rhythm",
"rimni": "rhyme",
"rinci": "to drain",
"rinju": "to restrain",
"rinka": "to cause",
"rinsa": "to greet",
"rirci": "rare",
"rirni": "parent",
"rirxe": "river",
"rismi": "rice",
"risna": "heart",
"ritli": "rite",
"rivbi": "to avoid",
"rokci": "rock",
"romge": "chrome",
"ropno": "European",
"rorci": "to procreate",
"rotsu": "thick",
"rozgu": "rose",
"ruble": "weak",
"rufsu": "rough",
"runme": "to melt",
"runta": "to dissolve",
"rupnu": "dollar",
"rusko": "Russian",
"rutni": "artifact",
"sabji": "to provide",
"sabnu": "cabin",
"sacki": "match",
"saclu": "decimal",
"sadjo": "Saudi",
"sakci": "to suck",
"sakli": "to slide",
"sakta": "sugar",
"salci": "to celebrate",
"salpo": "slope",
"salta": "salad",
"samcu": "cassava",
"sampu": "simple",
"sance": "sound",
"sanga": "to sing",
"sanji": "conscious",
"sanli": "to stand",
"sanmi": "meal",
"sanso": "sauce",
"santa": "umbrella",
"sarcu": "necessary",
"sarji": "to support",
"sarlu": "spiral",
"sarxe": "harmonious",
"saske": "science",
"satci": "exact",
"satre": "stroke",
"savru": "noise",
"sazri": "to operate",
"sefta": "surface",
"selci": "cell",
"selfu": "to serve",
"semto": "Semitic",
"senci": "sneeze",
"senpi": "to doubt",
"senta": "layer",
"senva": "to dream",
"sepli": "apart",
"serti": "stairs",
"setca": "to insert",
"sevzi": "self",
"sfani": "fly (insect)",
"sfasa": "to punish",
"sfofa": "sofa",
"sfubu": "to dive",
"siclu": "to whistle",
"sicni": "coin",
"sidbo": "idea",
"sidju": "to help",
"sigja": "cigar",
"silka": "silk",
"silna": "salt",
"simlu": "to seem",
"simsa": "similar",
"simxu": "mutual",
"since": "snake",
"sinma": "esteem",
"sinso": "sine",
"sinxa": "sign",
"sipna": "to sleep",
"sirji": "straight",
"sirxo": "Syrian",
"sisku": "to seek",
"sisti": "to cease",
"sitna": "to cite",
"sivni": "private",
"skaci": "skirt",
"skami": "computer",
"skapi": "pelt",
"skari": "color",
"skicu": "to describe",
"skiji": "ski",
"skina": "cinema",
"skori": "cord",
"skoto": "Scottish",
"skuro": "groove",
"slabu": "familiar",
"slaka": "syllable",
"slami": "acid",
"slanu": "cylinder",
"slari": "sour",
"slasi": "plastic",
"sligu": "solid",
"slilu": "to oscillate",
"sliri": "sulfur",
"slovo": "Slavic",
"sluji": "muscle",
"sluni": "onion",
"smacu": "mouse",
"smadi": "to guess",
"smaji": "quiet",
"smani": "monkey",
"smoka": "sock",
"smuci": "spoon",
"smuni": "meaning",
"snada": "to succeed",
"snanu": "south",
"snidu": "second",
"snime": "snow",
"snipa": "sticky",
"snuji": "sandwich",
"snura": "secure",
"snuti": "accidental",
"sobde": "soya",
"sodna": "sodium",
"sodva": "soda",
"softo": "Soviet",
"solji": "gold",
"solri": "solar",
"sombo": "to sow",
"sonci": "soldier",
"sorcu": "store",
"sorgu": "sorghum",
"sovda": "egg",
"spaji": "to surprise",
"spali": "to polish",
"spano": "Spanish",
"spati": "plant",
"speni": "married",
"spisa": "piece",
"spita": "hospital",
"spofu": "broken",
"spoja": "to explode",
"spuda": "to reply",
"sputu": "spit",
"sraji": "vertical",
"sraku": "to scratch",
"sralo": "Australian",
"srana": "to pertain",
"srasu": "grass",
"srera": "to err",
"srito": "Sanskrit",
"sruma": "to assume",
"sruri": "to surround",
"stace": "honest",
"stagi": "vegetable",
"staku": "ceramic",
"stali": "to remain",
"stani": "stalk",
"stapa": "to step",
"stasu": "soup",
"stati": "talent",
"steba": "frustration",
"steci": "specific",
"stedu": "head",
"stela": "lock",
"stero": "steradian",
"stici": "west",
"stidi": "to suggest",
"stika": "to adjust",
"stizu": "chair",
"stodi": "constant",
"stuna": "east",
"stura": "structure",
"stuzi": "site; position",
"sucta": "abstract",
"sudga": "dry",
"sufti": "hoof",
"suksa": "sudden",
"sumji": "sum",
"sumne": "to smell",
"sumti": "argument",
"sunga": "garlic",
"sunla": "wool",
"surla": "relax",
"sutra": "fast",
"tabno": "carbon",
"tabra": "trumpet",
"tadji": "method",
"tadni": "to study",
"tagji": "snug",
"talsa": "to challenge",
"tamca": "tomato",
"tamji": "thumb",
"tamne": "cousin",
"tanbo": "board",
"tance": "tongue",
"tanjo": "tangent",
"tanko": "tobacco",
"tanru": "(Lojban) tanru",
"tansi": "pan",
"tanxe": "box",
"tapla": "tile",
"tarbi": "embryo",
"tarci": "star",
"tarla": "tar",
"tarmi": "shape",
"tarti": "to behave",
"taske": "thirst",
"tatpi": "tired",
"tatru": "breast",
"tavla": "to talk",
"taxfu": "garment",
"tcaci": "custom",
"tcadu": "city",
"tcana": "station",
"tcati": "tea",
"tcena": "stretch",
"tcica": "to deceive",
"tcidu": "to read",
"tcika": "time of day",
"tcila": "detail",
"tcima": "weather",
"tcini": "situation",
"tcita": "label",
"temci": "time",
"tenfa": "exponential",
"tengu": "texture",
"terdi": "earth",
"terpa": "to fear",
"terto": "1E12",
"tigni": "to perform",
"tikpa": "to kick",
"tilju": "heavy",
"tinbe": "to obey",
"tinci": "tin",
"tinsa": "stiff",
"tirna": "to hear",
"tirse": "iron",
"tirxu": "tiger",
"tisna": "to fill",
"titla": "sweet",
"tivni": "television broadcaster",
"tixnu": "daughter",
"toknu": "oven",
"toldi": "butterfly",
"tonga": "tone",
"tordu": "short",
"torni": "twist",
"traji": "superlative",
"trano": "nitrogen",
"trati": "taut",
"trene": "train",
"tricu": "tree",
"trina": "to attract",
"trixe": "behind",
"troci": "to try",
"tsali": "strong",
"tsani": "sky",
"tsapi": "seasoning",
"tsiju": "seed",
"tsina": "stage",
"tubnu": "tube",
"tugni": "to agree",
"tujli": "tulip",
"tumla": "land",
"tunba": "sibling",
"tunka": "copper",
"tunlo": "to swallow",
"tunta": "to poke",
"tuple": "leg",
"turni": "to govern",
"tutci": "tool",
"tutra": "territory",
"vacri": "air",
"vajni": "important",
"valsi": "word",
"vamji": "value",
"vamtu": "to vomit",
"vanbi": "environment",
"vanci": "evening",
"vanju": "wine",
"vasru": "to contain",
"vasxu": "to breathe",
"vecnu": "to sell",
"venfu": "revenge",
"vensa": "spring",
"verba": "child",
"vibna": "vagina",
"vidni": "monitor",
"vidru": "virus",
"vifne": "fresh",
"vikmi": "excrete",
"viknu": "viscous",
"vimcu": "to remove",
"vindu": "poison",
"vinji": "airplane",
"vipsi": "deputy",
"virnu": "brave",
"viska": "to see",
"vitci": "irregular",
"vitke": "guest",
"vitno": "permanent",
"vlagi": "vulva",
"vlile": "violent",
"vlina": "alternation",
"vlipa": "powerful",
"vofli": "to fly",
"voksa": "voice",
"vorme": "door",
"vraga": "lever",
"vreji": "record",
"vreta": "reclining",
"vrici": "miscellaneous",
"vrude": "virtue",
"vrusi": "to taste",
"vukro": "Ukrainian",
"xabju": "resident; to inhabit",
"xadba": "half",
"xadni": "body",
"xagji": "hunger",
"xagri": "reed",
"xajmi": "funny",
"xaksu": "use up",
"xalbo": "levity",
"xalka": "alcohol",
"xalni": "to panic",
"xamgu": "good",
"xampo": "ampere",
"xamsi": "sea",
"xance": "hand",
"xanka": "nervous",
"xanri": "imaginary",
"xanto": "elephant",
"xarci": "weapon",
"xarju": "pig",
"xarnu": "stubborn",
"xasli": "donkey",
"xasne": "sweat",
"xatra": "letter",
"xatsi": "1E-18",
"xazdo": "Asiatic",
"xebni": "to hate",
"xebro": "Hebrew",
"xecto": "100",
"xedja": "jaw",
"xekri": "black",
"xelso": "Greek",
"xendo": "kind",
"xenru": "to regret",
"xexso": "1E18",
"xindo": "Hindi",
"xinmo": "ink",
"xirma": "horse",
"xislu": "wheel",
"xispo": "Hispanic",
"xlali": "bad",
"xlura": "to influence",
"xotli": "hotel",
"xrabo": "Arabic",
"xrani": "to injure",
"xriso": "Christian",
"xruba": "buckwheat",
"xruki": "turkey",
"xrula": "flower",
"xruti": "to return oneself",
"xukmi": "chemical",
"xunre": "red",
"xurdo": "Urdu",
"xusra": "to assert",
"xutla": "smooth",
"zabna": "favorable",
"zajba": "gymnast",
"zalvi": "to grind",
"zanru": "to approve",
"zarci": "market",
"zargu": "buttock",
"zasni": "temporary",
"zasti": "to exist",
"zbabu": "soap",
"zbani": "bay",
"zbasu": "to make",
"zbepi": "pedestal",
"zdani": "house; nest",
"zdile": "amusing",
"zekri": "crime",
"zenba": "to increase",
"zepti": "1E-21",
"zetro": "1E21",
"zgana": "to observe",
"zgike": "music",
"zifre": "free",
"zinki": "zinc",
"zirpu": "purple",
"zivle": "to invest",
"zmadu": "more",
"zmiku": "automatic",
"zukte": "to act",
"zumri": "maize",
"zungi": "guilt",
"zunle": "left",
"zunti": "to interfere",
"zutse": "to sit",
"zvati": "at"
}