var shortDescriptions = {};


// A: logical connectives
shortDescriptions["e"] = "and";
shortDescriptions["ji"] = "(connective ???)";
shortDescriptions["o"] = "if and only if";
shortDescriptions["a"] = "or";
shortDescriptions["u"] = "whether or not";

// JA: logical connectives
shortDescriptions["je"] = "and";
shortDescriptions["je'i"] = "(connective ???)";
shortDescriptions["jo"] = "if and only if";
shortDescriptions["ja"] = "or";
shortDescriptions["ju"] = "whether or not";

// JOI: non-logical connectives
shortDescriptions["joi"] = "and (mixed together)";

// BAI: sumtcita
shortDescriptions["du'o"] = "according to";
shortDescriptions["si'u"] = "aided by";
shortDescriptions["zau"] = "approved by";
shortDescriptions["ki'i"] = "as a relation of";
shortDescriptions["du'i"] = "as much as";
shortDescriptions["cu'u"] = "as said by";
shortDescriptions["tu'i"] = "associated with site";
shortDescriptions["ti'u"] = "associated with time";
shortDescriptions["di'o"] = "at the locus of";
shortDescriptions["ji'u"] = "based on";
shortDescriptions["ri'a"] = "because of cause";
shortDescriptions["ni'i"] = "because of logic";
shortDescriptions["mu'i"] = "because of motive";
shortDescriptions["ki'u"] = "because of reason";
shortDescriptions["va'u"] = "benefiting from";
shortDescriptions["koi"] = "bounded by";
shortDescriptions["ca'i"] = "by authority of";
shortDescriptions["ta'i"] = "by method";
shortDescriptions["pu'e"] = "by process";
shortDescriptions["ja'i"] = "by rule";
shortDescriptions["kai"] = "characterizing";
shortDescriptions["bai"] = "compelled by";
shortDescriptions["fi'e"] = "created by";
shortDescriptions["de'i"] = "dated";
shortDescriptions["ci'o"] = "emotionally felt by";
shortDescriptions["mau"] = "exceeded by";
shortDescriptions["mu'u"] = "exemplified by";
shortDescriptions["ri'i"] = "experienced by";
shortDescriptions["ra'i"] = "from source";
shortDescriptions["ka'a"] = "gone to by";
shortDescriptions["pa'u"] = "having component";
shortDescriptions["pa'a"] = "in addition to";
shortDescriptions["le'a"] = "in category";
shortDescriptions["ku'u"] = "in culture";
shortDescriptions["tai"] = "in form";
shortDescriptions["bau"] = "in language";
shortDescriptions["ma'i"] = "in reference frame";
shortDescriptions["ci'e"] = "in system";
shortDescriptions["fau"] = "in the event of";
shortDescriptions["po'i"] = "in the sequence";
shortDescriptions["cau"] = "lacked by";
shortDescriptions["ma'e"] = "material object";
shortDescriptions["ci'u"] = "on the scale";
shortDescriptions["ra'a"] = "pertained to by";
shortDescriptions["pu'a"] = "pleased by";
shortDescriptions["li'e"] = "preceded by";
shortDescriptions["la'u"] = "quantifying";
shortDescriptions["ba'i"] = "replaced by";
shortDescriptions["ka'i"] = "represented by";
shortDescriptions["sau"] = "requiring";
shortDescriptions["fa'e"] = "reverse of";
shortDescriptions["be'i"] = "sent by";
shortDescriptions["ti'i"] = "suggested by";
shortDescriptions["ja'e"] = "therefore result";
shortDescriptions["ga'a"] = "to observer";
shortDescriptions["va'o"] = "under conditions";
shortDescriptions["ji'o"] = "under direction of";
shortDescriptions["me'a"] = "undercut by";
shortDescriptions["do'e"] = "(unspecified modal)";
shortDescriptions["ji'e"] = "up to limit";
shortDescriptions["pi'o"] = "used by";
shortDescriptions["gau"] = "with active agent";
shortDescriptions["zu'e"] = "with actor";
shortDescriptions["me'e"] = "with name";
shortDescriptions["rai"] = "with superlative";

// BAhE: emphasis
shortDescriptions["ba'e"] = "(emphasized)";
shortDescriptions["za'e"] = "(nonce)";

// BE: first attached sumti
shortDescriptions["be"] = "(link sumti)";

// BEI: next attached sumti
shortDescriptions["bei"] = "(more sumti)";

// BEhO: fa'orma'o for BE ... BEI
shortDescriptions["be'o"] = "(end sumti)";

// BIhE: high priority
shortDescriptions["bi'e"] = "(high priority)";

// BIhI: non-logical interval connectives
shortDescriptions["mi'i"] = "(ordered) ... center";
shortDescriptions["bi'o"] = "(ordered) from ... to ...";
shortDescriptions["bi'i"] = "(unordered) between ... and ...";

// BO: short scope
shortDescriptions["bo"] = "(short scope link)";

// BOI: end numeral or letteral string
shortDescriptions["boi"] = "(end string)";

// BU: convert word to letteral
shortDescriptions["bu"] = "(letter)";

// BY: letterals
shortDescriptions["by"] = "B";
shortDescriptions["cy"] = "C";
shortDescriptions["dy"] = "D";
shortDescriptions["fy"] = "F";
shortDescriptions["gy"] = "G";
shortDescriptions["jy"] = "J";
shortDescriptions["ky"] = "K";
shortDescriptions["ly"] = "L";
shortDescriptions["my"] = "M";
shortDescriptions["ny"] = "N";
shortDescriptions["py"] = "P";
shortDescriptions["ry"] = "R";
shortDescriptions["sy"] = "S";
shortDescriptions["ty"] = "T";
shortDescriptions["vy"] = "V";
shortDescriptions["xy"] = "X";
shortDescriptions["y'y"] = "'";
shortDescriptions["zy"] = "Z";

/*
shortDescriptions["ga'e"] = "BY1";
shortDescriptions["ge'o"] = "BY1";
shortDescriptions["je'o"] = "BY1";
shortDescriptions["jo'o"] = "BY1";
shortDescriptions["lo'a"] = "BY1";
shortDescriptions["na'a"] = "BY1";
shortDescriptions["ru'o"] = "BY1";
shortDescriptions["se'e"] = "BY1";
shortDescriptions["to'a"] = "BY1";


// COI: vocative with meaning
shortDescriptions["coi"] = "COI";
shortDescriptions["co'o"] = "COI";
shortDescriptions["je'e"] = "COI";
shortDescriptions["nu'e"] = "COI";
shortDescriptions["ju'i"] = "COI";
shortDescriptions["ta'a"] = "COI";
shortDescriptions["pe'u"] = "COI";
shortDescriptions["ki'e"] = "COI";
shortDescriptions["fi'i"] = "COI";
shortDescriptions["be'e"] = "COI";
shortDescriptions["re'i"] = "COI";
shortDescriptions["mu'o"] = "COI";
shortDescriptions["vi'o"] = "COI";
shortDescriptions["ke'o"] = "COI";
shortDescriptions["fe'o"] = "COI";
shortDescriptions["mi'e"] = "COI";

// CU: separate selbri from preceding sumti
shortDescriptions["cu"] = "CU";

// DOI: vocative without meaning
shortDescriptions["doi"] = "DOI";

// FEhU: fa'orma'o for FIhO
shortDescriptions["fe'u"] = "FEhU";

// FIhO: start modal tag
shortDescriptions["fi'o"] = "FIhO";

// GEhU: fa'orma'o for GOI
shortDescriptions["ge'u"] = "GEhU";

// GOhA: pro-selbri
shortDescriptions["mo"] = "GOhA";
shortDescriptions["nei"] = "GOhA";
shortDescriptions["go'u"] = "GOhA";
shortDescriptions["go'o"] = "GOhA";
shortDescriptions["go'i"] = "GOhA";
shortDescriptions["no'a"] = "GOhA";
shortDescriptions["go'e"] = "GOhA";
shortDescriptions["go'a"] = "GOhA";
shortDescriptions["du"] = "GOhA";
shortDescriptions["bu'a"] = "GOhA";
shortDescriptions["bu'e"] = "GOhA";
shortDescriptions["bu'i"] = "GOhA";
shortDescriptions["co'e"] = "GOhA";

// GOI: relative phrase
shortDescriptions["pe"] = "GOI";
shortDescriptions["po"] = "GOI";
shortDescriptions["po'e"] = "GOI";
shortDescriptions["po'u"] = "GOI";
shortDescriptions["ne"] = "GOI";
shortDescriptions["no'u"] = "GOI";

// JOI: non-logical connectives (for all except bridi)
shortDescriptions["ce"] = "JOI";
shortDescriptions["ce'o"] = "JOI";
shortDescriptions["fa'u"] = "JOI";
shortDescriptions["jo'e"] = "JOI";
shortDescriptions["jo'u"] = "JOI";
shortDescriptions["joi"] = "JOI";
shortDescriptions["ju'e"] = "JOI";
shortDescriptions["ku'a"] = "JOI";
shortDescriptions["pi'u"] = "JOI";
shortDescriptions["ce'oi"] = "JOI";

// KOhA*: sumka'i
shortDescriptions["da"] = "KOhA1"
shortDescriptions["de"] = "KOhA1"
shortDescriptions["di"] = "KOhA1"
shortDescriptions["da'u"] = "KOhA2"
shortDescriptions["da'e"] = "KOhA2"
shortDescriptions["di'u"] = "KOhA2"
shortDescriptions["di'e"] = "KOhA2"
shortDescriptions["de'u"] = "KOhA2"
shortDescriptions["de'e"] = "KOhA2"
shortDescriptions["dei "] = "KOhA2"
shortDescriptions["do'i"] = "KOhA2"
shortDescriptions["ko"] = "KOhA3"
shortDescriptions["mi"] = "KOhA3"
shortDescriptions["mi'o"] = "KOhA3"
shortDescriptions["ma'a"] = "KOhA3"
shortDescriptions["mi'a"] = "KOhA3"
shortDescriptions["do"] = "KOhA3"
shortDescriptions["do'o"] = "KOhA3"
shortDescriptions["ko'a"] = "KOhA4"
shortDescriptions["fo'u"] = "KOhA4"
shortDescriptions["ko'e"] = "KOhA4"
shortDescriptions["ko'i"] = "KOhA4"
shortDescriptions["ko'o"] = "KOhA4"
shortDescriptions["ko'u"] = "KOhA4"
shortDescriptions["fo'a"] = "KOhA4"
shortDescriptions["fo'e"] = "KOhA4"
shortDescriptions["fo'i"] = "KOhA4"
shortDescriptions["fo'o"] = "KOhA4"
shortDescriptions["vo'a"] = "KOhA4"
shortDescriptions["vo'e"] = "KOhA4"
shortDescriptions["vo'i"] = "KOhA4"
shortDescriptions["vo'o"] = "KOhA4"
shortDescriptions["vo'u"] = "KOhA4"
shortDescriptions["ru"] = "KOhA5"
shortDescriptions["ri"] = "KOhA5"
shortDescriptions["ra"] = "KOhA5"
shortDescriptions["ta"] = "KOhA6"
shortDescriptions["tu"] = "KOhA6"
shortDescriptions["ti"] = "KOhA6"
shortDescriptions["zi'o"] = "KOhA7"
shortDescriptions["ke'a"] = "KOhA7"
shortDescriptions["ma"] = "KOhA7"
shortDescriptions["zu'i"] = "KOhA7"
shortDescriptions["zo'e"] = "KOhA7"
shortDescriptions["ce'u"] = "KOhA8"

// KU: fa'orma'o for LE and unfilled tags
shortDescriptions["ku"] = "KU";

// KUhO: fa'orma'o for NOI
shortDescriptions["ku'o"] = "KUhO";

// LA: gadri for names
shortDescriptions["la"] = "LA";
shortDescriptions["lai"] = "LA";
shortDescriptions["la'i"] = "LA";

// LE: gadri for objects
shortDescriptions["le"] = "LE";
shortDescriptions["lei"] = "LE";
shortDescriptions["loi"] = "LE";
shortDescriptions["lo"] = "LE";
shortDescriptions["le'i"] = "LE";
shortDescriptions["lo'i"] = "LE";
shortDescriptions["le'e"] = "LE";
shortDescriptions["lo'e"] = "LE";

// LI: gadri for numbers
shortDescriptions["li"] = "LI";
shortDescriptions["me'o"] = "LI";
shortDescriptions["li'ai"] = "LI";

// LIhU: fa'orma'o for LU
shortDescriptions["li'u"] = "LIhU";

// LU: grammatical quote
shortDescriptions["lu"] = "LU";
shortDescriptions["la'au"] = "LU";

// MOI
shortDescriptions["mei"] = "MOI";
shortDescriptions["moi"] = "MOI";
shortDescriptions["si'e"] = "MOI";
shortDescriptions["cu'o"] = "MOI";

// NOI: relative clauses
shortDescriptions["noi"] = "NOI";
shortDescriptions["poi"] = "NOI";
shortDescriptions["voi"] = "NOI";

// NU: abstractors
shortDescriptions["du'u"] = "NU";
shortDescriptions["jei"] = "NU";
shortDescriptions["ka"] = "NU";
shortDescriptions["jei"] = "NU";
shortDescriptions["li'i"] = "NU";
shortDescriptions["mu'e"] = "NU";
shortDescriptions["ni"] = "NU";
shortDescriptions["nu"] = "NU";
shortDescriptions["pu'u"] = "NU";
shortDescriptions["si'o"] = "NU";
shortDescriptions["su'u"] = "NU";
shortDescriptions["za'i"] = "NU";
shortDescriptions["zu'o"] = "NU";

shortDescriptions["ba"] = "PU";
shortDescriptions["pu"] = "PU";
shortDescriptions["ca"] = "PU";

shortDescriptions["se"] = "SE";
shortDescriptions["te"] = "SE";
shortDescriptions["ve"] = "SE";
shortDescriptions["xe"] = "SE";

// UI: indicators
shortDescriptions["i'a"] = "UI1";
shortDescriptions["ie"] = "UI1";
shortDescriptions["a'e"] = "UI1";
shortDescriptions["u'i"] = "UI1";
shortDescriptions["i'o"] = "UI1";
shortDescriptions["i'e"] = "UI1";
shortDescriptions["a'a"] = "UI1";
shortDescriptions["ia "] = "UI1";
shortDescriptions["o'i"] = "UI1";
shortDescriptions["o'e"] = "UI1";
shortDescriptions["e'e"] = "UI1";
shortDescriptions["oi"] = "UI1";
shortDescriptions["uo"] = "UI1";
shortDescriptions["e'i"] = "UI1";
shortDescriptions["u'o"] = "UI1";
shortDescriptions["au"] = "UI1";
shortDescriptions["ua"] = "UI1";
shortDescriptions["a'i"] = "UI1";
shortDescriptions["i'u"] = "UI1";
shortDescriptions["ii"] = "UI1";
shortDescriptions["u'a"] = "UI1";
shortDescriptions["ui"] = "UI1";
shortDescriptions["a'o"] = "UI1";
shortDescriptions["ai"] = "UI1";
shortDescriptions["a'u"] = "UI1";
shortDescriptions["iu"] = "UI1";
shortDescriptions["ei"] = "UI1";
shortDescriptions["o'o"] = "UI1";
shortDescriptions["e'a"] = "UI1";
shortDescriptions["uu"] = "UI1";
shortDescriptions["o'a"] = "UI1";
shortDescriptions["o'u"] = "UI1";
shortDescriptions["u'u"] = "UI1";
shortDescriptions["e'o"] = "UI1";
shortDescriptions["io"] = "UI1";
shortDescriptions["e'u"] = "UI1";
shortDescriptions["ue"] = "UI1";
shortDescriptions["i'i"] = "UI1";
shortDescriptions["u'e"] = "UI1";

shortDescriptions["ki'a"] = "UI6";
shortDescriptions["xu"] = "UI6";

shortDescriptions["vi"] = "VA";
shortDescriptions["va"] = "VA";
shortDescriptions["vu"] = "VA";

// ZIhE: join relatives
shortDescriptions["zi'e"] = "ZIhE";

// ZOI: non-Lojban quotes
shortDescriptions["zoi"] = "ZOI";
shortDescriptions["la'o"] = "ZOI";


*/



// pro-sumti
shortDescriptions["mi"] = "I; me"
shortDescriptions["do"] = "you"
shortDescriptions["ko"] = "you (!)"
shortDescriptions["ti"] = "this"
shortDescriptions["ta"] = "that"
shortDescriptions["tu"] = "that there"
shortDescriptions["ma"] = "(sumti ???)"
shortDescriptions["ke'a"] = "(relative reference)"

// descriptors
shortDescriptions["la"] = "the one named"
shortDescriptions["le"] = "the"
shortDescriptions["li"] = "the number"
shortDescriptions["lo"] = "a; some"

// attitudinals
shortDescriptions["ui"] = "(happy)"

// vocatives
shortDescriptions["coi"] = "hello"
shortDescriptions["doi"] = "(vocative)"
shortDescriptions["mi'e"] = "I am"
shortDescriptions["je'e"] = "okay"
shortDescriptions["co'o"] = "goodbye"

// tenses
shortDescriptions["pu"] = "did; before"
shortDescriptions["ca"] = "now; while"
shortDescriptions["ba"] = "will; after"

// abstractors
shortDescriptions["du'u"] = "expression of" // TODO expression?
shortDescriptions["nu"] = "event of"

// numbers
shortDescriptions["pa"] = "1"
shortDescriptions["re"] = "2"
shortDescriptions["ci"] = "3"
shortDescriptions["vo"] = "4"
shortDescriptions["mu"] = "5"
shortDescriptions["xa"] = "6"
shortDescriptions["ze"] = "7"
shortDescriptions["bi"] = "8"
shortDescriptions["so"] = "9"
shortDescriptions["no"] = "0"
shortDescriptions["ro"] = "all (of)"

// quotes
shortDescriptions["lu"] = "\""
shortDescriptions["li'u"] = "\""
shortDescriptions["zo"] = "(word quote)"
shortDescriptions["zoi"] = "(non-Lojban quote)"

// various cmavo
shortDescriptions["fa"] = "(place 1)"
shortDescriptions["fe"] = "(place 2)"
shortDescriptions["fi"] = "(place 3)"
shortDescriptions["fo"] = "(place 4)"
shortDescriptions["fu"] = "(place 5)"
shortDescriptions["se"] = "(swap 1 & 2)"
shortDescriptions["te"] = "(swap 1 & 3)"
shortDescriptions["ve"] = "(swap 1 & 4)"
shortDescriptions["xe"] = "(swap 1 & 5)"
shortDescriptions["cu"] = ""
shortDescriptions["zo'e"] = "something"
shortDescriptions["na"] = "not"
shortDescriptions["nai"] = "(negation)"
shortDescriptions["i"] = "."
shortDescriptions["ni'o"] = "(new topic)"
shortDescriptions["no'i"] = "(old topic)"
shortDescriptions["xu"] = "(yes/no ???)"

// pro-selbri
shortDescriptions["du"] = "to be equal to"
shortDescriptions["mo"] = "(selbri ???)"

// gismu
shortDescriptions["bacru"] = "to say; to utter"
shortDescriptions["badna"] = "banana"
shortDescriptions["badri"] = "sad"
shortDescriptions["bajra"] = "to run"
shortDescriptions["bakfu"] = "bundle"
shortDescriptions["bakni"] = "bovine"
shortDescriptions["bakri"] = "chalk"
shortDescriptions["baktu"] = "bucket"
shortDescriptions["balji"] = "bulb"
shortDescriptions["balni"] = "balcony"
shortDescriptions["balre"] = "blade"
shortDescriptions["balvi"] = "(in the) future"
shortDescriptions["bancu"] = "beyond"
shortDescriptions["bandu"] = "defend"
shortDescriptions["banfi"] = "amphibian"
shortDescriptions["bangu"] = "language"
shortDescriptions["banli"] = "great"
shortDescriptions["banro"] = "to grow"
shortDescriptions["banxa"] = "bank"
shortDescriptions["banzu"] = "to suffice"
shortDescriptions["bapli"] = "to force"
shortDescriptions["barda"] = "big"
shortDescriptions["bargu"] = "arch"
shortDescriptions["barja"] = "bar"
shortDescriptions["barna"] = "mark"
shortDescriptions["bartu"] = "out"
shortDescriptions["basna"] = "to emphasize"
shortDescriptions["basti"] = "to replace"
shortDescriptions["batci"] = "to bite"
shortDescriptions["batke"] = "button"
shortDescriptions["bavmi"] = "barley"
shortDescriptions["baxso"] = "Malay-Indonesian"
shortDescriptions["bebna"] = "foolish"
shortDescriptions["bemro"] = "North American"
shortDescriptions["bende"] = "crew"
shortDescriptions["bengo"] = "Bengali"
shortDescriptions["benji"] = "to transfer"
shortDescriptions["bersa"] = "son"
shortDescriptions["berti"] = "north"
shortDescriptions["besna"] = "brain"
shortDescriptions["betfu"] = "abdomen"
shortDescriptions["betri"] = "tragedy"
shortDescriptions["bevri"] = "carry"
shortDescriptions["bidju"] = "bead"
shortDescriptions["bifce"] = "bee"
shortDescriptions["bikla"] = "whip"
shortDescriptions["bilga"] = "obliged"
shortDescriptions["bilma"] = "ill"
shortDescriptions["bilni"] = "military"
shortDescriptions["bindo"] = "Indonesian"
shortDescriptions["binra"] = "to insure"
shortDescriptions["binxo"] = "to become"
shortDescriptions["birje"] = "beer"
shortDescriptions["birka"] = "arm"
shortDescriptions["birti"] = "certain"
shortDescriptions["bisli"] = "ice"
shortDescriptions["bitmu"] = "wall"
shortDescriptions["blabi"] = "white"
shortDescriptions["blaci"] = "glass"
shortDescriptions["blanu"] = "blue"
shortDescriptions["bliku"] = "block"
shortDescriptions["bloti"] = "boat"
shortDescriptions["bolci"] = "ball"
shortDescriptions["bongu"] = "bone"
shortDescriptions["botpi"] = "bottle"
shortDescriptions["boxfo"] = "sheet"
shortDescriptions["boxna"] = "wave"
shortDescriptions["bradi"] = "enemy"
shortDescriptions["bratu"] = "hail"
shortDescriptions["brazo"] = "Brazilian"
shortDescriptions["bredi"] = "ready"
shortDescriptions["bridi"] = "predicate"
shortDescriptions["brife"] = "breeze"
shortDescriptions["briju"] = "office"
shortDescriptions["brito"] = "British"
shortDescriptions["broda"] = "(predicate variable 1)"
shortDescriptions["brode"] = "(predicate variable 2)"
shortDescriptions["brodi"] = "(predicate variable 3)"
shortDescriptions["brodo"] = "(predicate variable 4)"
shortDescriptions["brodu"] = "(predicate variable 5)"
shortDescriptions["bruna"] = "brother"
shortDescriptions["budjo"] = "Buddhist"
shortDescriptions["bukpu"] = "cloth"
shortDescriptions["bumru"] = "fog"
shortDescriptions["bunda"] = "pound"
shortDescriptions["bunre"] = "brown"
shortDescriptions["burcu"] = "brush"
shortDescriptions["burna"] = "embarrassed"
shortDescriptions["cabna"] = "now"
shortDescriptions["cabra"] = "apparatus"
shortDescriptions["cacra"] = "hour" // TODO to be in?????? see djedi, nanca, masti
shortDescriptions["cadzu"] = "to walk"
shortDescriptions["cafne"] = "often"
shortDescriptions["cakla"] = "chocolate"
shortDescriptions["calku"] = "shell"
shortDescriptions["canci"] = "to vanish"
shortDescriptions["cando"] = "idle"
shortDescriptions["cange"] = "farm"
shortDescriptions["canja"] = "to exchange"
shortDescriptions["canko"] = "window"
shortDescriptions["canlu"] = "space"
shortDescriptions["canpa"] = "shovel"
shortDescriptions["canre"] = "sand"
shortDescriptions["canti"] = "gut"
shortDescriptions["carce"] = "cart"
shortDescriptions["carmi"] = "intense"
shortDescriptions["carna"] = "to turn"
shortDescriptions["cartu"] = "chart"
shortDescriptions["carvi"] = "rain"
shortDescriptions["casnu"] = "to discuss"
shortDescriptions["catke"] = "to shove"
shortDescriptions["catlu"] = "to look"
shortDescriptions["catni"] = "authority"
shortDescriptions["catra"] = "to kill"
shortDescriptions["caxno"] = "shallow"
shortDescriptions["cecla"] = "launcher"
shortDescriptions["cecmu"] = "community"
shortDescriptions["cedra"] = "era"
shortDescriptions["cenba"] = "to vary"
shortDescriptions["censa"] = "holy"
shortDescriptions["centi"] = ".01"
shortDescriptions["cerda"] = "heir"
shortDescriptions["cerni"] = "morning"
shortDescriptions["certu"] = "expert"
shortDescriptions["cevni"] = "god"
shortDescriptions["cfari"] = "to initiate"
shortDescriptions["cfika"] = "fiction"
shortDescriptions["cfila"] = "flaw"
shortDescriptions["cfine"] = "wedge"
shortDescriptions["cfipu"] = "confusing"
shortDescriptions["ciblu"] = "blood"
shortDescriptions["cicna"] = "cyan"
shortDescriptions["cidja"] = "food"
shortDescriptions["cidni"] = "knee"
shortDescriptions["cidro"] = "hydrogen"
shortDescriptions["cifnu"] = "infant"
shortDescriptions["cigla"] = "gland"
shortDescriptions["cikna"] = "awake"
shortDescriptions["cikre"] = "to repair"
shortDescriptions["ciksi"] = "to explain"
shortDescriptions["cilce"] = "wild"
shortDescriptions["cilmo"] = "moist"
shortDescriptions["cilre"] = "to learn"
shortDescriptions["cilta"] = "thread"
shortDescriptions["cimde"] = "dimension"
shortDescriptions["cimni"] = "infinite"
shortDescriptions["cinba"] = "to kiss"
shortDescriptions["cindu"] = "oak"
shortDescriptions["cinfo"] = "lion"
shortDescriptions["cinje"] = "to wrinkle"
shortDescriptions["cinki"] = "insect"
shortDescriptions["cinla"] = "thin"
shortDescriptions["cinmo"] = "emotion"
shortDescriptions["cinri"] = "interesting"
shortDescriptions["cinse"] = "sexual"
shortDescriptions["cinta"] = "paint"
shortDescriptions["cinza"] = "tongs"
shortDescriptions["cipni"] = "bird"
shortDescriptions["cipra"] = "test"
shortDescriptions["cirko"] = "to lose"
shortDescriptions["cirla"] = "cheese"
shortDescriptions["ciska"] = "to write"
shortDescriptions["cisma"] = "smile"
shortDescriptions["ciste"] = "system"
shortDescriptions["citka"] = "to eat"
shortDescriptions["citno"] = "young"
shortDescriptions["citri"] = "history"
shortDescriptions["citsi"] = "season"
shortDescriptions["civla"] = "louse"
shortDescriptions["cizra"] = "strange"
shortDescriptions["ckabu"] = "rubber"
shortDescriptions["ckafi"] = "coffee"
shortDescriptions["ckaji"] = "quality"
shortDescriptions["ckana"] = "bed"
shortDescriptions["ckape"] = "peril"
shortDescriptions["ckasu"] = "ridicule"
shortDescriptions["ckeji"] = "ashamed"
shortDescriptions["ckiku"] = "key"
shortDescriptions["ckilu"] = "scale"
shortDescriptions["ckini"] = "related"
shortDescriptions["ckire"] = "grateful"
shortDescriptions["ckule"] = "school"
shortDescriptions["ckunu"] = "conifer"
shortDescriptions["cladu"] = "loud"
shortDescriptions["clani"] = "long"
shortDescriptions["claxu"] = "without"
shortDescriptions["clika"] = "mossy"
shortDescriptions["clira"] = "early"
shortDescriptions["clite"] = "polite"
shortDescriptions["cliva"] = "to leave"
shortDescriptions["clupa"] = "loop"
shortDescriptions["cmaci"] = "mathematics"
shortDescriptions["cmalu"] = "small"
shortDescriptions["cmana"] = "mountain"
shortDescriptions["cmavo"] = "(Lojban) cmavo"
shortDescriptions["cmene"] = "name"
shortDescriptions["cmila"] = "to laugh"
shortDescriptions["cmima"] = "member"
shortDescriptions["cmoni"] = "moan"
shortDescriptions["cnano"] = "norm"
shortDescriptions["cnebo"] = "neck"
shortDescriptions["cnemu"] = "to reward"
shortDescriptions["cnici"] = "orderly"
shortDescriptions["cnino"] = "new"
shortDescriptions["cnisa"] = "lead"
shortDescriptions["cnita"] = "beneath"
shortDescriptions["cokcu"] = "to soak up"
shortDescriptions["condi"] = "deep"
shortDescriptions["cortu"] = "pain"
shortDescriptions["cpacu"] = "to get"
shortDescriptions["cpana"] = "upon"
shortDescriptions["cpare"] = "to climb"
shortDescriptions["cpedu"] = "to request"
shortDescriptions["cpina"] = "pungent"
shortDescriptions["cradi"] = "radio"
shortDescriptions["crane"] = "front"
shortDescriptions["creka"] = "shirt"
shortDescriptions["crepu"] = "to harvest"
shortDescriptions["cribe"] = "bear"
shortDescriptions["crida"] = "fairy"
shortDescriptions["crino"] = "green"
shortDescriptions["cripu"] = "bridge"
shortDescriptions["crisa"] = "summer"
shortDescriptions["critu"] = "autumn"
shortDescriptions["ctaru"] = "tide"
shortDescriptions["ctebi"] = "lip"
shortDescriptions["cteki"] = "tax"
shortDescriptions["ctile"] = "petroleum"
shortDescriptions["ctino"] = "shadow"
shortDescriptions["ctuca"] = "to teach"
shortDescriptions["cukla"] = "round"
shortDescriptions["cukta"] = "book"
shortDescriptions["culno"] = "full"
shortDescriptions["cumki"] = "possible"
shortDescriptions["cumla"] = "humble"
shortDescriptions["cunmi"] = "millet"
shortDescriptions["cunso"] = "random"
shortDescriptions["cuntu"] = "affair"
shortDescriptions["cupra"] = "to produce"
shortDescriptions["curmi"] = "to let; to permit"
shortDescriptions["curnu"] = "worm"
shortDescriptions["curve"] = "pure"
shortDescriptions["cusku"] = "to express; to say"
shortDescriptions["cutci"] = "shoe"
shortDescriptions["cutne"] = "chest"
shortDescriptions["cuxna"] = "to choose"
shortDescriptions["dacru"] = "drawer"
shortDescriptions["dacti"] = "object"
shortDescriptions["dadjo"] = "Taoist"
shortDescriptions["dakfu"] = "knife"
shortDescriptions["dakli"] = "sack"
shortDescriptions["damba"] = "to fight"
shortDescriptions["damri"] = "drum"
shortDescriptions["dandu"] = "hang"
shortDescriptions["danfu"] = "answer"
shortDescriptions["danlu"] = "animal"
shortDescriptions["danmo"] = "smoke"
shortDescriptions["danre"] = "pressure"
shortDescriptions["dansu"] = "to dance"
shortDescriptions["danti"] = "projectile"
shortDescriptions["daplu"] = "island"
shortDescriptions["dapma"] = "to curse"
shortDescriptions["dargu"] = "road"
shortDescriptions["darlu"] = "to argue"
shortDescriptions["darno"] = "far"
shortDescriptions["darsi"] = "audacity"
shortDescriptions["darxi"] = "to hit"
shortDescriptions["daski"] = "pocket"
shortDescriptions["dasni"] = "to wear"
shortDescriptions["daspo"] = "to destroy"
shortDescriptions["dasri"] = "ribbon"
shortDescriptions["datka"] = "duck"
shortDescriptions["datni"] = "data"
shortDescriptions["decti"] = ".1"
shortDescriptions["degji"] = "finger"
shortDescriptions["dejni"] = "owe"
shortDescriptions["dekpu"] = "gallon"
shortDescriptions["dekto"] = "10"
shortDescriptions["delno"] = "candela"
shortDescriptions["dembi"] = "bean"
shortDescriptions["denci"] = "tooth"
shortDescriptions["denmi"] = "dense"
shortDescriptions["denpa"] = "to wait"
shortDescriptions["dertu"] = "dirt"
shortDescriptions["derxi"] = "heap"
shortDescriptions["desku"] = "to shake"
shortDescriptions["detri"] = "date"
shortDescriptions["dicra"] = "to interrupt"
shortDescriptions["dikca"] = "electric"
shortDescriptions["diklo"] = "local"
shortDescriptions["dikni"] = "regular"
shortDescriptions["dilcu"] = "quotient"
shortDescriptions["dilnu"] = "cloud"
shortDescriptions["dimna"] = "fate"
shortDescriptions["dinju"] = "building"
shortDescriptions["dinko"] = "nail"
shortDescriptions["dirba"] = "dear"
shortDescriptions["dirce"] = "to radiate"
shortDescriptions["dirgo"] = "drop"
shortDescriptions["dizlo"] = "low"
shortDescriptions["djacu"] = "water"
shortDescriptions["djedi"] = "(to be in) day(s)"
shortDescriptions["djica"] = "to desire; to want"
shortDescriptions["djine"] = "ring"
shortDescriptions["djuno"] = "to know"
shortDescriptions["donri"] = "daytime"
shortDescriptions["dotco"] = "German"
shortDescriptions["draci"] = "drama"
shortDescriptions["drani"] = "correct"
shortDescriptions["drata"] = "other"
shortDescriptions["drudi"] = "roof"
shortDescriptions["dugri"] = "logarithm"
shortDescriptions["dukse"] = "to excess"
shortDescriptions["dukti"] = "opposite"
shortDescriptions["dunda"] = "to give"
shortDescriptions["dunja"] = "to freeze"
shortDescriptions["dunku"] = "anguished; stressed"
shortDescriptions["dunli"] = "to be equal to"
shortDescriptions["dunra"] = "winter"
shortDescriptions["dzena"] = "elder"
shortDescriptions["dzipo"] = "Antarctican"
shortDescriptions["facki"] = "to discover"
shortDescriptions["fadni"] = "ordinary"
shortDescriptions["fagri"] = "fire"
shortDescriptions["falnu"] = "sail"
shortDescriptions["famti"] = "aunt; uncle"
shortDescriptions["fancu"] = "function"
shortDescriptions["fange"] = "alien"
shortDescriptions["fanmo"] = "end"
shortDescriptions["fanri"] = "factory"
shortDescriptions["fanta"] = "to prevent"
shortDescriptions["fanva"] = "to translate"
shortDescriptions["fanza"] = "to annoy"
shortDescriptions["fapro"] = "to oppose"
shortDescriptions["farlu"] = "to fall"
shortDescriptions["farna"] = "direction"
shortDescriptions["farvi"] = "to develop"
shortDescriptions["fasnu"] = "event"
shortDescriptions["fatci"] = "fact"
shortDescriptions["fatne"] = "to reverse"
shortDescriptions["fatri"] = "to distribute"
shortDescriptions["febvi"] = "to boil"
shortDescriptions["femti"] = "1E-15"
shortDescriptions["fendi"] = "to divide"
shortDescriptions["fengu"] = "angry"
shortDescriptions["fenki"] = "crazy"
shortDescriptions["fenra"] = "crack"
shortDescriptions["fenso"] = "to sew"
shortDescriptions["fepni"] = "cent"
shortDescriptions["fepri"] = "lung"
shortDescriptions["ferti"] = "fertile"
shortDescriptions["festi"] = "waste"
shortDescriptions["fetsi"] = "female"
shortDescriptions["figre"] = "fig"
shortDescriptions["filso"] = "Palestinian"
shortDescriptions["finpe"] = "fish"
shortDescriptions["finti"] = "to invent"
shortDescriptions["flalu"] = "law"
shortDescriptions["flani"] = "flute"
shortDescriptions["flecu"] = "flow"
shortDescriptions["fliba"] = "to fail"
shortDescriptions["flira"] = "face"
shortDescriptions["foldi"] = "field"
shortDescriptions["fonmo"] = "foam"
shortDescriptions["fonxa"] = "telephone"
shortDescriptions["forca"] = "fork"
shortDescriptions["fraso"] = "French"
shortDescriptions["frati"] = "to react"
shortDescriptions["fraxu"] = "to forgive"
shortDescriptions["frica"] = "to differ"
shortDescriptions["friko"] = "African"
shortDescriptions["frili"] = "easy"
shortDescriptions["frinu"] = "fraction"
shortDescriptions["friti"] = "to offer"
shortDescriptions["frumu"] = "to frown"
shortDescriptions["fukpi"] = "to copy"
shortDescriptions["fulta"] = "to float"
shortDescriptions["funca"] = "luck"
shortDescriptions["fusra"] = "rotten"
shortDescriptions["fuzme"] = "responsible"
shortDescriptions["gacri"] = "cover"
shortDescriptions["gadri"] = "article"
shortDescriptions["galfi"] = "to modify"
shortDescriptions["galtu"] = "high"
shortDescriptions["galxe"] = "throat"
shortDescriptions["ganlo"] = "closed"
shortDescriptions["ganra"] = "broad"
shortDescriptions["ganse"] = "to sense"
shortDescriptions["ganti"] = "gonad"
shortDescriptions["ganxo"] = "anus"
shortDescriptions["ganzu"] = "to organize"
shortDescriptions["gapci"] = "gas"
shortDescriptions["gapru"] = "above"
shortDescriptions["garna"] = "rail"
shortDescriptions["gasnu"] = "to do"
shortDescriptions["gasta"] = "steel"
shortDescriptions["genja"] = "root"
shortDescriptions["gento"] = "Argentinian"
shortDescriptions["genxu"] = "hook"
shortDescriptions["gerku"] = "dog"
shortDescriptions["gerna"] = "grammar"
shortDescriptions["gidva"] = "to guide"
shortDescriptions["gigdo"] = "1E9"
shortDescriptions["ginka"] = "camp"
shortDescriptions["girzu"] = "group"
shortDescriptions["gismu"] = "(Lojban) gismu"
shortDescriptions["glare"] = "hot"
shortDescriptions["gleki"] = "happy"
shortDescriptions["gletu"] = "to copulate"
shortDescriptions["glico"] = "English"
shortDescriptions["gluta"] = "glove"
shortDescriptions["gocti"] = "1E-24"
shortDescriptions["gotro"] = "1E24"
shortDescriptions["gradu"] = "unit"
shortDescriptions["grake"] = "gram"
shortDescriptions["grana"] = "rod"
shortDescriptions["grasu"] = "grease"
shortDescriptions["greku"] = "frame"
shortDescriptions["grusi"] = "gray"
shortDescriptions["grute"] = "fruit"
shortDescriptions["gubni"] = "public"
shortDescriptions["gugde"] = "country"
shortDescriptions["gundi"] = "industry"
shortDescriptions["gunka"] = "to work"
shortDescriptions["gunma"] = "jointly"
shortDescriptions["gunro"] = "to roll"
shortDescriptions["gunse"] = "goose"
shortDescriptions["gunta"] = "to attack"
shortDescriptions["gurni"] = "grain"
shortDescriptions["guska"] = "to scrape; to erode"
shortDescriptions["gusni"] = "light; to illumine"
shortDescriptions["gusta"] = "restaurant"
shortDescriptions["gutci"] = "cubit"
shortDescriptions["gutra"] = "womb"
shortDescriptions["guzme"] = "melon"
shortDescriptions["jabre"] = "to brake"
shortDescriptions["jadni"] = "to decorate"
shortDescriptions["jakne"] = "rocket"
shortDescriptions["jalge"] = "result"
shortDescriptions["jalna"] = "starch"
shortDescriptions["jalra"] = "cockroach"
shortDescriptions["jamfu"] = "foot"
shortDescriptions["jamna"] = "to war"
shortDescriptions["janbe"] = "bell"
shortDescriptions["janco"] = "shoulder"
shortDescriptions["janli"] = "to collide"
shortDescriptions["jansu"] = "diplomat"
shortDescriptions["janta"] = "account"
shortDescriptions["jarbu"] = "suburb"
shortDescriptions["jarco"] = "to show"
shortDescriptions["jarki"] = "narrow"
shortDescriptions["jaspu"] = "passport"
shortDescriptions["jatna"] = "captain"
shortDescriptions["javni"] = "rule"
shortDescriptions["jbama"] = "bomb"
shortDescriptions["jbari"] = "berry"
shortDescriptions["jbena"] = "born"
shortDescriptions["jbera"] = "to borrow"
shortDescriptions["jbini"] = "between"
shortDescriptions["jdari"] = "firm"
shortDescriptions["jdice"] = "to decide"
shortDescriptions["jdika"] = "to decrease"
shortDescriptions["jdima"] = "price"
shortDescriptions["jdini"] = "money"
shortDescriptions["jduli"] = "jelly"
shortDescriptions["jecta"] = "polity"
shortDescriptions["jeftu"] = "week"
shortDescriptions["jegvo"] = "Jehovist"
shortDescriptions["jelca"] = "to burn"
shortDescriptions["jemna"] = "gem"
shortDescriptions["jenca"] = "to shock"
shortDescriptions["jendu"] = "axle"
shortDescriptions["jenmi"] = "army"
shortDescriptions["jerna"] = "to earn"
shortDescriptions["jersi"] = "to chase"
shortDescriptions["jerxo"] = "Algerian"
shortDescriptions["jesni"] = "needle"
shortDescriptions["jetce"] = "jet"
shortDescriptions["jetnu"] = "true"
shortDescriptions["jgalu"] = "claw"
shortDescriptions["jganu"] = "angle"
shortDescriptions["jgari"] = "to grasp; to hold"
shortDescriptions["jgena"] = "knot"
shortDescriptions["jgina"] = "gene"
shortDescriptions["jgira"] = "pride"
shortDescriptions["jgita"] = "guitar"
shortDescriptions["jibni"] = "near"
shortDescriptions["jibri"] = "job"
shortDescriptions["jicla"] = "stir"
shortDescriptions["jicmu"] = "basis"
shortDescriptions["jijnu"] = "intuit"
shortDescriptions["jikca"] = "to socialize"
shortDescriptions["jikru"] = "liquor"
shortDescriptions["jilka"] = "alkali"
shortDescriptions["jilra"] = "jealous"
shortDescriptions["jimca"] = "branch"
shortDescriptions["jimpe"] = "to understand"
shortDescriptions["jimte"] = "limit"
shortDescriptions["jinci"] = "shears"
shortDescriptions["jinga"] = "to win"
shortDescriptions["jinku"] = "vaccine"
shortDescriptions["jinme"] = "metal"
shortDescriptions["jinru"] = "to immerse"
shortDescriptions["jinsa"] = "clean"
shortDescriptions["jinto"] = "well; spring"
shortDescriptions["jinvi"] = "to opine"
shortDescriptions["jinzi"] = "innate property"
shortDescriptions["jipci"] = "chicken"
shortDescriptions["jipno"] = "tip"
shortDescriptions["jirna"] = "horn"
shortDescriptions["jisra"] = "juice"
shortDescriptions["jitfa"] = "false"
shortDescriptions["jitro"] = "to control; to manage"
shortDescriptions["jivbu"] = "to weave"
shortDescriptions["jivna"] = "to compete"
shortDescriptions["jmaji"] = "to gather"
shortDescriptions["jmifa"] = "shoal"
shortDescriptions["jmina"] = "to add"
shortDescriptions["jmive"] = "to live"
shortDescriptions["jordo"] = "Jordanian"
shortDescriptions["jorne"] = "joined"
shortDescriptions["jubme"] = "table"
shortDescriptions["judri"] = "address"
shortDescriptions["jufra"] = "sentence; text"
shortDescriptions["jukni"] = "spider"
shortDescriptions["jukpa"] = "to cook"
shortDescriptions["julne"] = "net"
shortDescriptions["jundi"] = "attentive"
shortDescriptions["jungo"] = "Chinese"
shortDescriptions["junla"] = "clock"
shortDescriptions["junri"] = "serious"
shortDescriptions["junta"] = "weight"
shortDescriptions["jurme"] = "germ"
shortDescriptions["jursa"] = "severe"
shortDescriptions["jutsi"] = "species"
shortDescriptions["juxre"] = "clumsy"
shortDescriptions["jvinu"] = "view"
shortDescriptions["kabri"] = "cup"
shortDescriptions["kacma"] = "camera"
shortDescriptions["kadno"] = "Canadian"
shortDescriptions["kafke"] = "to cough"
shortDescriptions["kagni"] = "company"
shortDescriptions["kajde"] = "to warn"
shortDescriptions["kajna"] = "shelf"
shortDescriptions["kakne"] = "to be able to"
shortDescriptions["kakpa"] = "to dig"
shortDescriptions["kalci"] = "feces"
shortDescriptions["kalri"] = "open"
shortDescriptions["kalsa"] = "chaotic"
shortDescriptions["kalte"] = "to hunt"
shortDescriptions["kamju"] = "column"
shortDescriptions["kamni"] = "committee"
shortDescriptions["kampu"] = "common"
shortDescriptions["kanba"] = "goat"
shortDescriptions["kancu"] = "to count"
shortDescriptions["kandi"] = "dim"
shortDescriptions["kanji"] = "calculate"
shortDescriptions["kanla"] = "eye"
shortDescriptions["kanro"] = "healthy"
shortDescriptions["kansa"] = "with"
shortDescriptions["kantu"] = "quantum"
shortDescriptions["kanxe"] = "conjunction"
shortDescriptions["karbi"] = "to compare"
shortDescriptions["karce"] = "car"
shortDescriptions["karda"] = "card"
shortDescriptions["kargu"] = "costly"
shortDescriptions["karli"] = "collar"
shortDescriptions["karni"] = "journal"
shortDescriptions["katna"] = "to cut"
shortDescriptions["kavbu"] = "to capture"
shortDescriptions["kecti"] = "pity"
shortDescriptions["kelci"] = "to play"
shortDescriptions["kelvo"] = "kelvin"
shortDescriptions["kenra"] = "cancer"
shortDescriptions["kensa"] = "outer space"
shortDescriptions["kerfa"] = "hair"
shortDescriptions["kerlo"] = "ear"
shortDescriptions["ketco"] = "South American"
shortDescriptions["kevna"] = "cavity"
shortDescriptions["kibro"] = "internet"
shortDescriptions["kicne"] = "cushion"
shortDescriptions["kijno"] = "oxygen"
shortDescriptions["kilto"] = "1000"
shortDescriptions["kinda"] = "kind of"
shortDescriptions["kinli"] = "sharp"
shortDescriptions["kisto"] = "Pakistani"
shortDescriptions["klaji"] = "street"
shortDescriptions["klaku"] = "to weep"
shortDescriptions["klama"] = "to come"
shortDescriptions["klani"] = "quantity"
shortDescriptions["klesi"] = "class"
shortDescriptions["klina"] = "clear"
shortDescriptions["kliru"] = "chlorine"
shortDescriptions["kliti"] = "clay"
shortDescriptions["klupe"] = "screw"
shortDescriptions["kluza"] = "loose"
shortDescriptions["kobli"] = "cabbage"
shortDescriptions["kojna"] = "corner"
shortDescriptions["kolme"] = "coal"
shortDescriptions["komcu"] = "to comb"
shortDescriptions["konju"] = "cone"
shortDescriptions["korbi"] = "edge"
shortDescriptions["korcu"] = "bent"
shortDescriptions["korka"] = "cork"
shortDescriptions["kosta"] = "coat"
shortDescriptions["kramu"] = "acre"
shortDescriptions["krasi"] = "source"
shortDescriptions["krati"] = "to represent"
shortDescriptions["krefu"] = "recurrence; repetition"
shortDescriptions["krici"] = "to believe"
shortDescriptions["krili"] = "crystal"
shortDescriptions["krinu"] = "reason"
shortDescriptions["krixa"] = "to cry out"
shortDescriptions["kruca"] = "to intersect"
shortDescriptions["kruji"] = "cream"
shortDescriptions["kruvi"] = "curve"
shortDescriptions["kubli"] = "cube"
shortDescriptions["kucli"] = "curious"
shortDescriptions["kufra"] = "comfort"
shortDescriptions["kukte"] = "delicious"
shortDescriptions["kulnu"] = "culture"
shortDescriptions["kumfa"] = "room"
shortDescriptions["kumte"] = "camel"
shortDescriptions["kunra"] = "mineral"
shortDescriptions["kunti"] = "empty"
shortDescriptions["kurfa"] = "square"
shortDescriptions["kurji"] = "to take care of"
shortDescriptions["kurki"] = "bitter"
shortDescriptions["kuspe"] = "to range; to span"
shortDescriptions["kusru"] = "cruel"
shortDescriptions["labno"] = "wolf"
shortDescriptions["lacpu"] = "to pull"
shortDescriptions["lacri"] = "to rely"
shortDescriptions["ladru"] = "milk"
shortDescriptions["lafti"] = "lift"
shortDescriptions["lakne"] = "probable"
shortDescriptions["lakse"] = "wax"
shortDescriptions["lalxu"] = "lake"
shortDescriptions["lamji"] = "adjacent"
shortDescriptions["lanbi"] = "protein"
shortDescriptions["lanci"] = "flag"
shortDescriptions["lanka"] = "basket"
shortDescriptions["lanli"] = "to analyze"
shortDescriptions["lanme"] = "sheep"
shortDescriptions["lante"] = "can"
shortDescriptions["lanxe"] = "to balance"
shortDescriptions["lanzu"] = "family"
shortDescriptions["larcu"] = "art"
shortDescriptions["lasna"] = "to fasten"
shortDescriptions["lastu"] = "brass"
shortDescriptions["latmo"] = "Latin"
shortDescriptions["latna"] = "lotus"
shortDescriptions["lazni"] = "lazy"
shortDescriptions["lebna"] = "to take"
shortDescriptions["lenjo"] = "lens"
shortDescriptions["lenku"] = "cold"
shortDescriptions["lerci"] = "late"
shortDescriptions["lerfu"] = "letteral"
shortDescriptions["libjo"] = "Libyan"
shortDescriptions["lidne"] = "to precede"
shortDescriptions["lifri"] = "to experience"
shortDescriptions["lijda"] = "religion"
shortDescriptions["limna"] = "to swim"
shortDescriptions["lindi"] = "lightning"
shortDescriptions["linji"] = "line"
shortDescriptions["linsi"] = "chain"
shortDescriptions["linto"] = "lightweight"
shortDescriptions["lisri"] = "story"
shortDescriptions["liste"] = "list"
shortDescriptions["litce"] = "liter"
shortDescriptions["litki"] = "liquid"
shortDescriptions["litru"] = "to travel"
shortDescriptions["livga"] = "liver"
shortDescriptions["livla"] = "fuel"
shortDescriptions["logji"] = "logic"
shortDescriptions["lojbo"] = "Lojbanic"
shortDescriptions["loldi"] = "floor"
shortDescriptions["lorxu"] = "fox"
shortDescriptions["lubno"] = "Lebanese"
shortDescriptions["lujvo"] = "(Lojban) lujvo"
shortDescriptions["lumci"] = "to wash"
shortDescriptions["lunbe"] = "bare"
shortDescriptions["lunra"] = "lunar"
shortDescriptions["lunsa"] = "to condense"
shortDescriptions["mabla"] = "derogative"
shortDescriptions["mabru"] = "mammal"
shortDescriptions["macnu"] = "manual"
shortDescriptions["makcu"] = "mature"
shortDescriptions["makfa"] = "magic"
shortDescriptions["maksi"] = "magnet"
shortDescriptions["malsi"] = "temple"
shortDescriptions["mamta"] = "mother"
shortDescriptions["manci"] = "to wonder"
shortDescriptions["manfo"] = "uniform"
shortDescriptions["manku"] = "dark"
shortDescriptions["manri"] = "reference"
shortDescriptions["mansa"] = "to satisfy"
shortDescriptions["manti"] = "ant"
shortDescriptions["mapku"] = "cap"
shortDescriptions["mapni"] = "cotton"
shortDescriptions["mapti"] = "to fit"
shortDescriptions["marbi"] = "shelter"
shortDescriptions["marce"] = "vehicle"
shortDescriptions["marde"] = "ethics; morals"
shortDescriptions["margu"] = "mercury"
shortDescriptions["marji"] = "material"
shortDescriptions["marna"] = "hemp"
shortDescriptions["marxa"] = "to mash"
shortDescriptions["masno"] = "slow"
shortDescriptions["masti"] = "(to be in) month(s)"
shortDescriptions["matci"] = "mat"
shortDescriptions["matli"] = "linen"
shortDescriptions["matne"] = "butter"
shortDescriptions["matra"] = "motor"
shortDescriptions["mavji"] = "oats"
shortDescriptions["maxri"] = "wheat"
shortDescriptions["mebri"] = "brow"
shortDescriptions["megdo"] = "1E6"
shortDescriptions["mekso"] = "mathematical expression"
shortDescriptions["melbi"] = "beautiful"
shortDescriptions["meljo"] = "Malaysian"
shortDescriptions["menli"] = "mind"
shortDescriptions["mensi"] = "sister"
shortDescriptions["mentu"] = "minute"
shortDescriptions["merko"] = "American"
shortDescriptions["merli"] = "to measure"
shortDescriptions["mexno"] = "Mexican"
shortDescriptions["midju"] = "middle"
shortDescriptions["mifra"] = "code"
shortDescriptions["mikce"] = "doctor"
shortDescriptions["mikri"] = "1E-6"
shortDescriptions["milti"] = ".001"
shortDescriptions["milxe"] = "mild"
shortDescriptions["minde"] = "to command"
shortDescriptions["minji"] = "machine"
shortDescriptions["minli"] = "mile"
shortDescriptions["minra"] = "to reflect"
shortDescriptions["mintu"] = "same"
shortDescriptions["mipri"] = "secret"
shortDescriptions["mirli"] = "deer"
shortDescriptions["misno"] = "famous"
shortDescriptions["misro"] = "Egyptian"
shortDescriptions["mitre"] = "meter"
shortDescriptions["mixre"] = "mixture"
shortDescriptions["mlana"] = "side"
shortDescriptions["mlatu"] = "cat"
shortDescriptions["mleca"] = "less"
shortDescriptions["mledi"] = "mold"
shortDescriptions["mluni"] = "satellite"
shortDescriptions["mokca"] = "point"
shortDescriptions["moklu"] = "mouth"
shortDescriptions["molki"] = "mill"
shortDescriptions["molro"] = "mole"
shortDescriptions["morji"] = "to remember"
shortDescriptions["morko"] = "Moroccan"
shortDescriptions["morna"] = "pattern"
shortDescriptions["morsi"] = "dead"
shortDescriptions["mosra"] = "friction"
shortDescriptions["mraji"] = "rye"
shortDescriptions["mrilu"] = "to mail"
shortDescriptions["mruli"] = "hammer"
shortDescriptions["mucti"] = "immaterial"
shortDescriptions["mudri"] = "wood"
shortDescriptions["mukti"] = "motive"
shortDescriptions["mulno"] = "complete"
shortDescriptions["munje"] = "universe"
shortDescriptions["mupli"] = "example"
shortDescriptions["murse"] = "glimmering"
shortDescriptions["murta"] = "curtain"
shortDescriptions["muslo"] = "Islamic"
shortDescriptions["mutce"] = "much"
shortDescriptions["muvdu"] = "to move"
shortDescriptions["muzga"] = "museum"
shortDescriptions["nabmi"] = "problem"
shortDescriptions["nakni"] = "male"
shortDescriptions["nalci"] = "wing"
shortDescriptions["namcu"] = "number"
shortDescriptions["nanba"] = "bread"
shortDescriptions["nanca"] = "(to be in) year(s)"
shortDescriptions["nandu"] = "difficult"
shortDescriptions["nanla"] = "boy"
shortDescriptions["nanmu"] = "man"
shortDescriptions["nanvi"] = "1E-9"
shortDescriptions["narge"] = "nut"
shortDescriptions["narju"] = "orange"
shortDescriptions["natfe"] = "to deny"
shortDescriptions["natmi"] = "nation"
shortDescriptions["navni"] = "neon"
shortDescriptions["naxle"] = "canal"
shortDescriptions["nazbi"] = "nose"
shortDescriptions["nejni"] = "energy"
shortDescriptions["nelci"] = "to like"
shortDescriptions["nenri"] = "in"
shortDescriptions["nibli"] = "to necessitate"
shortDescriptions["nicte"] = "night"
shortDescriptions["nikle"] = "nickel"
shortDescriptions["nilce"] = "furniture"
shortDescriptions["nimre"] = "citrus"
shortDescriptions["ninmu"] = "woman"
shortDescriptions["nirna"] = "nerve"
shortDescriptions["nitcu"] = "to need"
shortDescriptions["nivji"] = "to knit"
shortDescriptions["nixli"] = "girl"
shortDescriptions["nobli"] = "noble"
shortDescriptions["notci"] = "message"
shortDescriptions["nukni"] = "magenta"
shortDescriptions["nupre"] = "to promise"
shortDescriptions["nurma"] = "rural"
shortDescriptions["nutli"] = "neutral"
shortDescriptions["nuzba"] = "news"
shortDescriptions["pacna"] = "to hope"
shortDescriptions["pagbu"] = "part"
shortDescriptions["pagre"] = "pass through"
shortDescriptions["pajni"] = "judge"
shortDescriptions["palci"] = "evil"
shortDescriptions["palku"] = "pants"
shortDescriptions["palne"] = "tray"
shortDescriptions["palpi"] = "palpate"
shortDescriptions["palta"] = "plate"
shortDescriptions["pambe"] = "pump"
shortDescriptions["panci"] = "odor"
shortDescriptions["pandi"] = "punctuate"
shortDescriptions["panje"] = "sponge"
shortDescriptions["panka"] = "park"
shortDescriptions["panlo"] = "slice"
shortDescriptions["panpi"] = "peace"
shortDescriptions["panra"] = "parallel"
shortDescriptions["pante"] = "to protest"
shortDescriptions["panzi"] = "offspring"
shortDescriptions["papri"] = "page"
shortDescriptions["parbi"] = "ratio"
shortDescriptions["pastu"] = "robe"
shortDescriptions["patfu"] = "father"
shortDescriptions["patlu"] = "potato"
shortDescriptions["patxu"] = "pot"
shortDescriptions["pelji"] = "paper"
shortDescriptions["pelxu"] = "yellow"
shortDescriptions["pemci"] = "poem"
shortDescriptions["penbi"] = "pen"
shortDescriptions["pencu"] = "to touch"
shortDescriptions["pendo"] = "friend"
shortDescriptions["penmi"] = "to meet"
shortDescriptions["pensi"] = "to think"
shortDescriptions["perli"] = "pear"
shortDescriptions["pesxu"] = "paste"
shortDescriptions["petso"] = "1E15"
shortDescriptions["pezli"] = "leaf"
shortDescriptions["picti"] = "1E-12"
shortDescriptions["pijne"] = "pin"
shortDescriptions["pikci"] = "to beg"
shortDescriptions["pikta"] = "ticket"
shortDescriptions["pilji"] = "to multiply"
shortDescriptions["pilka"] = "crust"
shortDescriptions["pilno"] = "to use"
shortDescriptions["pimlu"] = "feather"
shortDescriptions["pinca"] = "urine"
shortDescriptions["pindi"] = "poor"
shortDescriptions["pinfu"] = "prisoner"
shortDescriptions["pinji"] = "penis"
shortDescriptions["pinka"] = "to comment"
shortDescriptions["pinsi"] = "pencil"
shortDescriptions["pinta"] = "level"
shortDescriptions["pinxe"] = "to drink"
shortDescriptions["pipno"] = "piano"
shortDescriptions["pixra"] = "picture"
shortDescriptions["plana"] = "plump"
shortDescriptions["platu"] = "to plan"
shortDescriptions["pleji"] = "to pay"
shortDescriptions["plibu"] = "pubic"
shortDescriptions["plini"] = "planet"
shortDescriptions["plipe"] = "to leap"
shortDescriptions["plise"] = "apple"
shortDescriptions["plita"] = "plane"
shortDescriptions["plixa"] = "to plow"
shortDescriptions["pluja"] = "complicated"
shortDescriptions["pluka"] = "pleasant"
shortDescriptions["pluta"] = "route"
shortDescriptions["polje"] = "to fold"
shortDescriptions["polno"] = "Polynesian"
shortDescriptions["ponjo"] = "Japanese"
shortDescriptions["ponse"] = "to own"
shortDescriptions["porpi"] = "break"
shortDescriptions["porsi"] = "sequence"
shortDescriptions["porto"] = "Portuguese"
shortDescriptions["prali"] = "to profit"
shortDescriptions["prami"] = "to love"
shortDescriptions["prane"] = "perfect"
shortDescriptions["preja"] = "to spread"
shortDescriptions["prenu"] = "person"
shortDescriptions["preti"] = "question"
shortDescriptions["prije"] = "wise"
shortDescriptions["prina"] = "to print"
shortDescriptions["pritu"] = "right"
shortDescriptions["prosa"] = "prose"
shortDescriptions["pruce"] = "process"
shortDescriptions["pruni"] = "elastic"
shortDescriptions["pruxi"] = "spirit"
shortDescriptions["pulce"] = "dust"
shortDescriptions["pulji"] = "police"
shortDescriptions["pulni"] = "pulley"
shortDescriptions["punji"] = "to put"
shortDescriptions["punli"] = "swelling"
shortDescriptions["purci"] = "past"
shortDescriptions["purdi"] = "garden"
shortDescriptions["purmo"] = "powder"
shortDescriptions["racli"] = "sane"
shortDescriptions["ractu"] = "rabbit"
shortDescriptions["radno"] = "radian"
shortDescriptions["rafsi"] = "affix"
shortDescriptions["ragve"] = "across"
shortDescriptions["rakso"] = "Iraqi"
shortDescriptions["raktu"] = "to trouble"
shortDescriptions["ralci"] = "delicate"
shortDescriptions["ralju"] = "principal"
shortDescriptions["ralte"] = "to retain"
shortDescriptions["randa"] = "to yield"
shortDescriptions["rango"] = "organ"
shortDescriptions["ranji"] = "to continue"
shortDescriptions["ranmi"] = "myth"
shortDescriptions["ransu"] = "bronze"
shortDescriptions["ranti"] = "soft"
shortDescriptions["ranxi"] = "irony"
shortDescriptions["rapli"] = "to repeat"
shortDescriptions["rarna"] = "natural"
shortDescriptions["ratcu"] = "rat"
shortDescriptions["ratni"] = "atom"
shortDescriptions["rebla"] = "tail"
shortDescriptions["rectu"] = "meat"
shortDescriptions["remna"] = "human"
shortDescriptions["renro"] = "to throw"
shortDescriptions["renvi"] = "to survive"
shortDescriptions["respa"] = "reptile"
shortDescriptions["ricfu"] = "rich"
shortDescriptions["rigni"] = "disgusting"
shortDescriptions["rijno"] = "silver"
shortDescriptions["rilti"] = "rhythm"
shortDescriptions["rimni"] = "rhyme"
shortDescriptions["rinci"] = "to drain"
shortDescriptions["rinju"] = "to restrain"
shortDescriptions["rinka"] = "to cause"
shortDescriptions["rinsa"] = "to greet"
shortDescriptions["rirci"] = "rare"
shortDescriptions["rirni"] = "parent"
shortDescriptions["rirxe"] = "river"
shortDescriptions["rismi"] = "rice"
shortDescriptions["risna"] = "heart"
shortDescriptions["ritli"] = "rite"
shortDescriptions["rivbi"] = "to avoid"
shortDescriptions["rokci"] = "rock"
shortDescriptions["romge"] = "chrome"
shortDescriptions["ropno"] = "European"
shortDescriptions["rorci"] = "to procreate"
shortDescriptions["rotsu"] = "thick"
shortDescriptions["rozgu"] = "rose"
shortDescriptions["ruble"] = "weak"
shortDescriptions["rufsu"] = "rough"
shortDescriptions["runme"] = "to melt"
shortDescriptions["runta"] = "to dissolve"
shortDescriptions["rupnu"] = "dollar"
shortDescriptions["rusko"] = "Russian"
shortDescriptions["rutni"] = "artifact"
shortDescriptions["sabji"] = "to provide"
shortDescriptions["sabnu"] = "cabin"
shortDescriptions["sacki"] = "match"
shortDescriptions["saclu"] = "decimal"
shortDescriptions["sadjo"] = "Saudi"
shortDescriptions["sakci"] = "to suck"
shortDescriptions["sakli"] = "to slide"
shortDescriptions["sakta"] = "sugar"
shortDescriptions["salci"] = "to celebrate"
shortDescriptions["salpo"] = "slope"
shortDescriptions["salta"] = "salad"
shortDescriptions["samcu"] = "cassava"
shortDescriptions["sampu"] = "simple"
shortDescriptions["sance"] = "sound"
shortDescriptions["sanga"] = "to sing"
shortDescriptions["sanji"] = "conscious"
shortDescriptions["sanli"] = "to stand"
shortDescriptions["sanmi"] = "meal"
shortDescriptions["sanso"] = "sauce"
shortDescriptions["santa"] = "umbrella"
shortDescriptions["sarcu"] = "necessary"
shortDescriptions["sarji"] = "to support"
shortDescriptions["sarlu"] = "spiral"
shortDescriptions["sarxe"] = "harmonious"
shortDescriptions["saske"] = "science"
shortDescriptions["satci"] = "exact"
shortDescriptions["satre"] = "stroke"
shortDescriptions["savru"] = "noise"
shortDescriptions["sazri"] = "to operate"
shortDescriptions["sefta"] = "surface"
shortDescriptions["selci"] = "cell"
shortDescriptions["selfu"] = "to serve"
shortDescriptions["semto"] = "Semitic"
shortDescriptions["senci"] = "sneeze"
shortDescriptions["senpi"] = "to doubt"
shortDescriptions["senta"] = "layer"
shortDescriptions["senva"] = "to dream"
shortDescriptions["sepli"] = "apart"
shortDescriptions["serti"] = "stairs"
shortDescriptions["setca"] = "to insert"
shortDescriptions["sevzi"] = "self"
shortDescriptions["sfani"] = "fly" // the insect
shortDescriptions["sfasa"] = "to punish"
shortDescriptions["sfofa"] = "sofa"
shortDescriptions["sfubu"] = "to dive"
shortDescriptions["siclu"] = "to whistle"
shortDescriptions["sicni"] = "coin"
shortDescriptions["sidbo"] = "idea"
shortDescriptions["sidju"] = "to help"
shortDescriptions["sigja"] = "cigar"
shortDescriptions["silka"] = "silk"
shortDescriptions["silna"] = "salt"
shortDescriptions["simlu"] = "to seem"
shortDescriptions["simsa"] = "similar"
shortDescriptions["simxu"] = "mutual"
shortDescriptions["since"] = "snake"
shortDescriptions["sinma"] = "esteem"
shortDescriptions["sinso"] = "sine"
shortDescriptions["sinxa"] = "sign"
shortDescriptions["sipna"] = "to sleep"
shortDescriptions["sirji"] = "straight"
shortDescriptions["sirxo"] = "Syrian"
shortDescriptions["sisku"] = "to seek"
shortDescriptions["sisti"] = "to cease"
shortDescriptions["sitna"] = "to cite"
shortDescriptions["sivni"] = "private"
shortDescriptions["skaci"] = "skirt"
shortDescriptions["skami"] = "computer"
shortDescriptions["skapi"] = "pelt"
shortDescriptions["skari"] = "color"
shortDescriptions["skicu"] = "to describe"
shortDescriptions["skiji"] = "ski"
shortDescriptions["skina"] = "cinema"
shortDescriptions["skori"] = "cord"
shortDescriptions["skoto"] = "Scottish"
shortDescriptions["skuro"] = "groove"
shortDescriptions["slabu"] = "familiar"
shortDescriptions["slaka"] = "syllable"
shortDescriptions["slami"] = "acid"
shortDescriptions["slanu"] = "cylinder"
shortDescriptions["slari"] = "sour"
shortDescriptions["slasi"] = "plastic"
shortDescriptions["sligu"] = "solid"
shortDescriptions["slilu"] = "to oscillate"
shortDescriptions["sliri"] = "sulfur"
shortDescriptions["slovo"] = "Slavic"
shortDescriptions["sluji"] = "muscle"
shortDescriptions["sluni"] = "onion"
shortDescriptions["smacu"] = "mouse"
shortDescriptions["smadi"] = "to guess"
shortDescriptions["smaji"] = "quiet"
shortDescriptions["smani"] = "monkey"
shortDescriptions["smoka"] = "sock"
shortDescriptions["smuci"] = "spoon"
shortDescriptions["smuni"] = "meaning"
shortDescriptions["snada"] = "to succeed"
shortDescriptions["snanu"] = "south"
shortDescriptions["snidu"] = "second"
shortDescriptions["snime"] = "snow"
shortDescriptions["snipa"] = "sticky"
shortDescriptions["snuji"] = "sandwich"
shortDescriptions["snura"] = "secure"
shortDescriptions["snuti"] = "accidental"
shortDescriptions["sobde"] = "soya"
shortDescriptions["sodna"] = "sodium"
shortDescriptions["sodva"] = "soda"
shortDescriptions["softo"] = "Soviet"
shortDescriptions["solji"] = "gold"
shortDescriptions["solri"] = "solar"
shortDescriptions["sombo"] = "to sow"
shortDescriptions["sonci"] = "soldier"
shortDescriptions["sorcu"] = "store"
shortDescriptions["sorgu"] = "sorghum"
shortDescriptions["sovda"] = "egg"
shortDescriptions["spaji"] = "to surprise"
shortDescriptions["spali"] = "to polish"
shortDescriptions["spano"] = "Spanish"
shortDescriptions["spati"] = "plant"
shortDescriptions["speni"] = "married"
shortDescriptions["spisa"] = "piece"
shortDescriptions["spita"] = "hospital"
shortDescriptions["spofu"] = "broken"
shortDescriptions["spoja"] = "to explode"
shortDescriptions["spuda"] = "to reply"
shortDescriptions["sputu"] = "spit"
shortDescriptions["sraji"] = "vertical"
shortDescriptions["sraku"] = "to scratch"
shortDescriptions["sralo"] = "Australian"
shortDescriptions["srana"] = "to pertain"
shortDescriptions["srasu"] = "grass"
shortDescriptions["srera"] = "to err"
shortDescriptions["srito"] = "Sanskrit"
shortDescriptions["sruma"] = "to assume"
shortDescriptions["sruri"] = "to surround"
shortDescriptions["stace"] = "honest"
shortDescriptions["stagi"] = "vegetable"
shortDescriptions["staku"] = "ceramic"
shortDescriptions["stali"] = "to remain"
shortDescriptions["stani"] = "stalk"
shortDescriptions["stapa"] = "to step"
shortDescriptions["stasu"] = "soup"
shortDescriptions["stati"] = "talent"
shortDescriptions["steba"] = "frustration"
shortDescriptions["steci"] = "specific"
shortDescriptions["stedu"] = "head"
shortDescriptions["stela"] = "lock"
shortDescriptions["stero"] = "steradian"
shortDescriptions["stici"] = "west"
shortDescriptions["stidi"] = "to suggest"
shortDescriptions["stika"] = "to adjust"
shortDescriptions["stizu"] = "chair"
shortDescriptions["stodi"] = "constant"
shortDescriptions["stuna"] = "east"
shortDescriptions["stura"] = "structure"
shortDescriptions["stuzi"] = "site; position"
shortDescriptions["sucta"] = "abstract"
shortDescriptions["sudga"] = "dry"
shortDescriptions["sufti"] = "hoof"
shortDescriptions["suksa"] = "sudden"
shortDescriptions["sumji"] = "sum"
shortDescriptions["sumne"] = "to smell"
shortDescriptions["sumti"] = "argument"
shortDescriptions["sunga"] = "garlic"
shortDescriptions["sunla"] = "wool"
shortDescriptions["surla"] = "relax"
shortDescriptions["sutra"] = "fast"
shortDescriptions["tabno"] = "carbon"
shortDescriptions["tabra"] = "trumpet"
shortDescriptions["tadji"] = "method"
shortDescriptions["tadni"] = "to study"
shortDescriptions["tagji"] = "snug"
shortDescriptions["talsa"] = "to challenge"
shortDescriptions["tamca"] = "tomato"
shortDescriptions["tamji"] = "thumb"
shortDescriptions["tamne"] = "cousin"
shortDescriptions["tanbo"] = "board"
shortDescriptions["tance"] = "tongue"
shortDescriptions["tanjo"] = "tangent"
shortDescriptions["tanko"] = "tobacco"
shortDescriptions["tanru"] = "(Lojban) tanru"
shortDescriptions["tansi"] = "pan"
shortDescriptions["tanxe"] = "box"
shortDescriptions["tapla"] = "tile"
shortDescriptions["tarbi"] = "embryo"
shortDescriptions["tarci"] = "star"
shortDescriptions["tarla"] = "tar"
shortDescriptions["tarmi"] = "shape"
shortDescriptions["tarti"] = "to behave"
shortDescriptions["taske"] = "thirst"
shortDescriptions["tatpi"] = "tired"
shortDescriptions["tatru"] = "breast"
shortDescriptions["tavla"] = "to talk"
shortDescriptions["taxfu"] = "garment"
shortDescriptions["tcaci"] = "custom"
shortDescriptions["tcadu"] = "city"
shortDescriptions["tcana"] = "station"
shortDescriptions["tcati"] = "tea"
shortDescriptions["tcena"] = "stretch"
shortDescriptions["tcica"] = "to deceive"
shortDescriptions["tcidu"] = "to read"
shortDescriptions["tcika"] = "time of day"
shortDescriptions["tcila"] = "detail"
shortDescriptions["tcima"] = "weather"
shortDescriptions["tcini"] = "situation"
shortDescriptions["tcita"] = "label"
shortDescriptions["temci"] = "time"
shortDescriptions["tenfa"] = "exponential"
shortDescriptions["tengu"] = "texture"
shortDescriptions["terdi"] = "earth"
shortDescriptions["terpa"] = "to fear"
shortDescriptions["terto"] = "1E12"
shortDescriptions["tigni"] = "to perform"
shortDescriptions["tikpa"] = "to kick"
shortDescriptions["tilju"] = "heavy"
shortDescriptions["tinbe"] = "to obey"
shortDescriptions["tinci"] = "tin"
shortDescriptions["tinsa"] = "stiff"
shortDescriptions["tirna"] = "to hear"
shortDescriptions["tirse"] = "iron"
shortDescriptions["tirxu"] = "tiger"
shortDescriptions["tisna"] = "to fill"
shortDescriptions["titla"] = "sweet"
shortDescriptions["tivni"] = "television broadcaster"
shortDescriptions["tixnu"] = "daughter"
shortDescriptions["toknu"] = "oven"
shortDescriptions["toldi"] = "butterfly"
shortDescriptions["tonga"] = "tone"
shortDescriptions["tordu"] = "short"
shortDescriptions["torni"] = "twist"
shortDescriptions["traji"] = "superlative"
shortDescriptions["trano"] = "nitrogen"
shortDescriptions["trati"] = "taut"
shortDescriptions["trene"] = "train"
shortDescriptions["tricu"] = "tree"
shortDescriptions["trina"] = "to attract"
shortDescriptions["trixe"] = "behind"
shortDescriptions["troci"] = "to try"
shortDescriptions["tsali"] = "strong"
shortDescriptions["tsani"] = "sky"
shortDescriptions["tsapi"] = "seasoning"
shortDescriptions["tsiju"] = "seed"
shortDescriptions["tsina"] = "stage"
shortDescriptions["tubnu"] = "tube"
shortDescriptions["tugni"] = "to agree"
shortDescriptions["tujli"] = "tulip"
shortDescriptions["tumla"] = "land"
shortDescriptions["tunba"] = "sibling"
shortDescriptions["tunka"] = "copper"
shortDescriptions["tunlo"] = "to swallow"
shortDescriptions["tunta"] = "to poke"
shortDescriptions["tuple"] = "leg"
shortDescriptions["turni"] = "to govern"
shortDescriptions["tutci"] = "tool"
shortDescriptions["tutra"] = "territory"
shortDescriptions["vacri"] = "air"
shortDescriptions["vajni"] = "important"
shortDescriptions["valsi"] = "word"
shortDescriptions["vamji"] = "value"
shortDescriptions["vamtu"] = "to vomit"
shortDescriptions["vanbi"] = "environment"
shortDescriptions["vanci"] = "evening"
shortDescriptions["vanju"] = "wine"
shortDescriptions["vasru"] = "to contain"
shortDescriptions["vasxu"] = "to breathe"
shortDescriptions["vecnu"] = "to sell"
shortDescriptions["venfu"] = "revenge"
shortDescriptions["vensa"] = "spring"
shortDescriptions["verba"] = "child"
shortDescriptions["vibna"] = "vagina"
shortDescriptions["vidni"] = "monitor"
shortDescriptions["vidru"] = "virus"
shortDescriptions["vifne"] = "fresh"
shortDescriptions["vikmi"] = "excrete"
shortDescriptions["viknu"] = "viscous"
shortDescriptions["vimcu"] = "to remove"
shortDescriptions["vindu"] = "poison"
shortDescriptions["vinji"] = "airplane"
shortDescriptions["vipsi"] = "deputy"
shortDescriptions["virnu"] = "brave"
shortDescriptions["viska"] = "to see"
shortDescriptions["vitci"] = "irregular"
shortDescriptions["vitke"] = "guest"
shortDescriptions["vitno"] = "permanent"
shortDescriptions["vlagi"] = "vulva"
shortDescriptions["vlile"] = "violent"
shortDescriptions["vlina"] = "alternation"
shortDescriptions["vlipa"] = "powerful"
shortDescriptions["vofli"] = "to fly"
shortDescriptions["voksa"] = "voice"
shortDescriptions["vorme"] = "door"
shortDescriptions["vraga"] = "lever"
shortDescriptions["vreji"] = "record"
shortDescriptions["vreta"] = "reclining"
shortDescriptions["vrici"] = "miscellaneous"
shortDescriptions["vrude"] = "virtue"
shortDescriptions["vrusi"] = "to taste"
shortDescriptions["vukro"] = "Ukrainian"
shortDescriptions["xabju"] = "resident; to inhabit"
shortDescriptions["xadba"] = "half"
shortDescriptions["xadni"] = "body"
shortDescriptions["xagji"] = "hunger"
shortDescriptions["xagri"] = "reed"
shortDescriptions["xajmi"] = "funny"
shortDescriptions["xaksu"] = "use up"
shortDescriptions["xalbo"] = "levity"
shortDescriptions["xalka"] = "alcohol"
shortDescriptions["xalni"] = "to panic"
shortDescriptions["xamgu"] = "good"
shortDescriptions["xampo"] = "ampere"
shortDescriptions["xamsi"] = "sea"
shortDescriptions["xance"] = "hand"
shortDescriptions["xanka"] = "nervous"
shortDescriptions["xanri"] = "imaginary"
shortDescriptions["xanto"] = "elephant"
shortDescriptions["xarci"] = "weapon"
shortDescriptions["xarju"] = "pig"
shortDescriptions["xarnu"] = "stubborn"
shortDescriptions["xasli"] = "donkey"
shortDescriptions["xasne"] = "sweat"
shortDescriptions["xatra"] = "letter"
shortDescriptions["xatsi"] = "1E-18"
shortDescriptions["xazdo"] = "Asiatic"
shortDescriptions["xebni"] = "to hate"
shortDescriptions["xebro"] = "Hebrew"
shortDescriptions["xecto"] = "100"
shortDescriptions["xedja"] = "jaw"
shortDescriptions["xekri"] = "black"
shortDescriptions["xelso"] = "Greek"
shortDescriptions["xendo"] = "kind"
shortDescriptions["xenru"] = "to regret"
shortDescriptions["xexso"] = "1E18"
shortDescriptions["xindo"] = "Hindi"
shortDescriptions["xinmo"] = "ink"
shortDescriptions["xirma"] = "horse"
shortDescriptions["xislu"] = "wheel"
shortDescriptions["xispo"] = "Hispanic"
shortDescriptions["xlali"] = "bad"
shortDescriptions["xlura"] = "to influence"
shortDescriptions["xotli"] = "hotel"
shortDescriptions["xrabo"] = "Arabic"
shortDescriptions["xrani"] = "to injure"
shortDescriptions["xriso"] = "Christian"
shortDescriptions["xruba"] = "buckwheat"
shortDescriptions["xruki"] = "turkey"
shortDescriptions["xrula"] = "flower"
shortDescriptions["xruti"] = "to return oneself"
shortDescriptions["xukmi"] = "chemical"
shortDescriptions["xunre"] = "red"
shortDescriptions["xurdo"] = "Urdu"
shortDescriptions["xusra"] = "to assert"
shortDescriptions["xutla"] = "smooth"
shortDescriptions["zabna"] = "favorable"
shortDescriptions["zajba"] = "gymnast"
shortDescriptions["zalvi"] = "to grind"
shortDescriptions["zanru"] = "to approve"
shortDescriptions["zarci"] = "market"
shortDescriptions["zargu"] = "buttock"
shortDescriptions["zasni"] = "temporary"
shortDescriptions["zasti"] = "to exist"
shortDescriptions["zbabu"] = "soap"
shortDescriptions["zbani"] = "bay"
shortDescriptions["zbasu"] = "to make"
shortDescriptions["zbepi"] = "pedestal"
shortDescriptions["zdani"] = "house; nest"
shortDescriptions["zdile"] = "amusing"
shortDescriptions["zekri"] = "crime"
shortDescriptions["zenba"] = "to increase"
shortDescriptions["zepti"] = "1E-21"
shortDescriptions["zetro"] = "1E21"
shortDescriptions["zgana"] = "to observe"
shortDescriptions["zgike"] = "music"
shortDescriptions["zifre"] = "free"
shortDescriptions["zinki"] = "zinc"
shortDescriptions["zirpu"] = "purple"
shortDescriptions["zivle"] = "to invest"
shortDescriptions["zmadu"] = "more"
shortDescriptions["zmiku"] = "automatic"
shortDescriptions["zukte"] = "to act"
shortDescriptions["zumri"] = "maize"
shortDescriptions["zungi"] = "guilt"
shortDescriptions["zunle"] = "left"
shortDescriptions["zunti"] = "to interfere"
shortDescriptions["zutse"] = "to sit"
shortDescriptions["zvati"] = "at"

module.exports.shortDescriptions = shortDescriptions
